INSERT INTO FA_OP_CLIENT_LOAN_BALANCE
SELECT CLIENT_CODE,
FACILITY_CODE,
TRNDATE,
DRCR_STATUS,
TRNAMOUNT*-1,
PROC_DESC,
SYSDATE, --ENTDATE,
'SNALL', --ENT_USER,
DOCREF_NO,
RPT_TRNAMOUNT,
TRN_CURRENCY,
VALUE_DATE
FROM FA_OP_CLIENT_LOAN_BALANCE
WHERE FACILITY_CODE='RBL201507-0118' 
AND DOCREF_NO='FR-20150826-004852'
/

INSERT INTO CO_FN_ACC_LICENCEE_GEN_ACCOUNT
SELECT
DIVISION_CODE,
PRODUCT_CODE,
TRNDATE,
ACC_TYPE_CODE,
DRCR_STATUS,
TRNAMOUNT,
DOCREFNO,
SYSDATE,--ENTDATE,
ACC_SYS_REFNO,
PROC_DESC,
CORR_ACC_NO,
TRANSACTION_CODE,
'SNALL',--ENT_USER,
LOCATION_CODE
FROM CO_FN_ACC_LICENCEE_GEN_ACCOUNT
WHERE DOCREFNO='FR-20150826-004852' 
AND PROC_DESC='SETTLEMENT DEPOSIT' 
and TRNAMOUNT='5362.24'
/

-- ============================================================================
-- ============================================================================


DECLARE

      M_FACILITY_CODE VARCHAR2(30) := 'RBL201507-0118';
      M_DOCREF_NO     VARCHAR2(30) := 'FR-20150826-004852';
      M_TRNAMOUNT     NUMBER(24,2) := 0;
      
BEGIN
      
      SELECT DISTINCT TRNAMOUNT
      INTO M_TRNAMOUNT
      FROM FA_OP_CLIENT_LOAN_BALANCE
      WHERE FACILITY_CODE=M_FACILITY_CODE 
      AND DOCREF_NO=M_DOCREF_NO;
      
      INSERT INTO FA_OP_CLIENT_LOAN_BALANCE_BK
      SELECT CLIENT_CODE,
      FACILITY_CODE,
      TRNDATE,
      DRCR_STATUS,
      TRNAMOUNT,
      PROC_DESC,
      ENTDATE,
      ENT_USER,
      DOCREF_NO,
      RPT_TRNAMOUNT,
      TRN_CURRENCY,
      VALUE_DATE
      FROM FA_OP_CLIENT_LOAN_BALANCE
      WHERE FACILITY_CODE=M_FACILITY_CODE 
      AND DOCREF_NO=M_DOCREF_NO;
      
      INSERT INTO FA_OP_CLIENT_LOAN_BALANCE
      SELECT CLIENT_CODE,
      FACILITY_CODE,
      TRNDATE,
      DRCR_STATUS,
      TRNAMOUNT*-1,
      PROC_DESC,
      SYSDATE, --ENTDATE,
      'SNALL', --ENT_USER,
      DOCREF_NO,
      RPT_TRNAMOUNT*-1,
      TRN_CURRENCY,
      VALUE_DATE
      FROM FA_OP_CLIENT_LOAN_BALANCE
      WHERE FACILITY_CODE=M_FACILITY_CODE 
      AND DOCREF_NO=M_DOCREF_NO;
      
      -- --------------------------------------------------------------------
      
      INSERT INTO CO_FN_ACC_LICENCEE_GEN_ACC_BK
      SELECT
      DIVISION_CODE,
      PRODUCT_CODE,
      TRNDATE,
      ACC_TYPE_CODE,
      DRCR_STATUS,
      TRNAMOUNT,
      DOCREFNO,
      ENTDATE,
      ACC_SYS_REFNO,
      PROC_DESC,
      CORR_ACC_NO,
      TRANSACTION_CODE,
      ENT_USER,
      LOCATION_CODE
      FROM CO_FN_ACC_LICENCEE_GEN_ACCOUNT
      WHERE DOCREFNO=M_DOCREF_NO 
      AND PROC_DESC='SETTLEMENT DEPOSIT' 
      and TRNAMOUNT=M_TRNAMOUNT;
      
      INSERT INTO CO_FN_ACC_LICENCEE_GEN_ACCOUNT
      SELECT
      DIVISION_CODE,
      PRODUCT_CODE,
      TRNDATE,
      ACC_TYPE_CODE,
      DRCR_STATUS,
      TRNAMOUNT*-1,
      DOCREFNO,
      SYSDATE,--ENTDATE,
      ACC_SYS_REFNO,
      PROC_DESC,
      CORR_ACC_NO,
      TRANSACTION_CODE,
      'SNALL',--ENT_USER,
      LOCATION_CODE
      FROM CO_FN_ACC_LICENCEE_GEN_ACCOUNT
      WHERE DOCREFNO=M_DOCREF_NO
      AND PROC_DESC='SETTLEMENT DEPOSIT' 
      and TRNAMOUNT=M_TRNAMOUNT;
      
      COMMIT;


END;

