// DEVELOP BY : MAHELA FOR OFSCL FACTORING    DATE:22-12-2006
    
import java.io.*; 
import javax.servlet.*; 
import javax.servlet.http.*; 
import java.sql.*; 
import java.util.*; 
 
  
public class LAKDL_FA_OP_display_debtor_creation extends javax.servlet.http.HttpServlet { 

	ServletOutputStream out = null;
	Connection conn;
	public ResultSet rs,rs1;
	Statement stmt;
	String m_client_code,m_facility_no;
	
	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
		 
		try { 
			 
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String m_header_name=m_sn_methods.header_name.trim();
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			conn = m_sn_methods.met_user_validate(req); 
			stmt=conn.createStatement();
			out = res.getOutputStream(); 
			
			m_facility_no=req.getParameter("facility_no");
			m_client_code=req.getParameter("client_code");	
			
						 
			out.println("<HTML>"); 
			out.println("<HEAD>"); 
			out.println("<TITLE>Operation Process - Debtor Creation </TITLE>"); 
			out.println("</HEAD>"); 
			out.println("<link REL='STYLESHEET' HREF='"+m_html_client_url+"/css/Asset_Financing_System.css' TYPE=\"text/css\">"); 
			out.println("<SCRIPT language=\"JavaScript\">"); 
			 
			out.println("var m_sav_msg='';");
	  	out.println("var m_submit=false;");
			
			out.println("function get_vector(data_vec) {");
			out.println("		if(data_vec.length>0 && document.Form1.hid_display_client.value==\"1\"){");
			out.println("    	if(data_vec[1]==\"C\"){");
			out.println("    	document.Form1.TXT_CLIENT_LEGAL_ST_BUSINESS.value=data_vec[37];");
			out.println("    	document.Form1.TXT_ISSUED_SHARE_CAPITAL.value=data_vec[39];");
			out.println("    	document.Form1.TXT_BUSINESS_CERTIFICATE_NO.value=data_vec[38];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_DD.value=data_vec[40];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_MM.value=data_vec[41];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_YY.value=data_vec[42];");
			out.println("    	document.Form1.TXT_VAT_REG_NO.value=data_vec[43];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_DD.value=data_vec[44];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_MM.value=data_vec[45];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_YY.value=data_vec[46];");
			out.println("    	document.Form1.TXT_WITH_HOLDING_TAX.value=data_vec[47];");
			out.println("    	}");
			out.println("    	else{");
			out.println("    	document.Form1.TXT_CLIENT_TITLE.value=data_vec[50];");
			out.println("    	document.Form1.TXT_CLIENT_FNAME.value=data_vec[51];");
			out.println("    	document.Form1.TXT_CLIENT_SNAME.value=data_vec[52];");
			out.println("    	document.Form1.TXT_CLIENT_INITIALS.value=data_vec[53];");
			out.println("    	document.Form1.TXT_CLIENT_ONAME.value=data_vec[54];");
			out.println("    	document.Form1.TXT_CLIENT_IDNO.value=data_vec[48];");
			out.println("    	document.Form1.TXT_CLIENT_PASSPORT.value=data_vec[49];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_DD.value=data_vec[55];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_MM.value=data_vec[56];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_YY.value=data_vec[57];");
			out.println("    	document.Form1.TXT_GENDER.value=data_vec[58];");
			out.println("    	}");
			out.println("    	document.Form1.TXT_CLIENT_GROUP.value=data_vec[6];");
			out.println("    	document.Form1.TXT_CLIENT_CRIB.value=data_vec[7];");
			out.println("			enable_comment(document.Form1.TXT_CLIENT_CRIB.value)");
			out.println("    	document.Form1.TXT_CLIENT_CRIB_COMMENT.value=data_vec[8];");
			out.println("			if(data_vec[59] != \"\" ) { ");
			out.println("    	document.Form1.TXT_3RD_PARTY_STATUS.selectedIndex=0;");
			out.println("			enable_specify(document.Form1.TXT_3RD_PARTY_STATUS.value);");
			out.println("    	}");
			out.println("    	document.Form1.TXT_3RD_PARTY_DEBTOR_DET.value=data_vec[59];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_STATUS.value=data_vec[9];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_ADDRESS1.value=data_vec[10];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_TELEPHONE.value=data_vec[15];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_ADDRESS2.value=data_vec[11];");
			out.println("    	document.Form1.TXT_CLIENT_OFFICE_TELEPHONE.value=data_vec[16];");
			out.println("    	document.Form1.TXT_CLIENT_CITY.value=data_vec[12];");
			out.println("    	document.Form1.TXT_CLIENT_FAXNO.value=data_vec[17];");
			out.println("    	document.Form1.TXT_CLIENT_COLLECTION_AREA.value=data_vec[13];");
			out.println("    	document.Form1.TXT_CLIENT_MOBILE.value=data_vec[19];");
			out.println("    	document.Form1.TXT_CLIENT_REFERENCE.value=data_vec[14];");
			out.println("    	document.Form1.TXT_CLIENT_EMAIL.value=data_vec[18];");
			out.println("    	document.Form1.TXT_CLIENT_KEY_DECISION_MAKER.value=data_vec[20];");
			out.println("    	document.Form1.TXT_CLIENT_CONT_PERSON.value=data_vec[21];");
			out.println("    	document.Form1.TXT_CLIENT_DESIG_PAYMENT.value=data_vec[22];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_STATUS.value=data_vec[23];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_ADDRESS1.value=data_vec[24];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_TELEPHONE.value=data_vec[27];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_ADDRESS2.value=data_vec[25];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_FAX.value=data_vec[28];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_EMAIL.value=data_vec[29];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_CONPERSON.value=data_vec[26];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_STATUS.value=data_vec[30];");
			out.println("    	document.Form1.TXT_CORESSS_HOMEADDRESS1.value=data_vec[31];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_TELEPHONE.value=data_vec[34];");
			out.println("    	document.Form1.TXT_CORESSS_HOMEADDRESS2.value=data_vec[32];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_FAX.value=data_vec[35];");
			out.println("    	document.Form1.TXT_CORESSS_CITY.value=data_vec[33];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_EMAIL.value=data_vec[36];");
			//out.println("  		makeRequest(2);");
			out.println("		}");
			//------------leasing
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"20\"){");
			out.println("    	if(data_vec[1]==\"C\"){");
			out.println("    	document.Form1.TXT_CLIENT_LEGAL_ST_BUSINESS.value=data_vec[37];");
			out.println("    	document.Form1.TXT_ISSUED_SHARE_CAPITAL.value=data_vec[39];");
			out.println("    	document.Form1.TXT_BUSINESS_CERTIFICATE_NO.value=data_vec[38];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_DD.value=data_vec[40];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_MM.value=data_vec[41];");
			out.println("    	document.Form1.TXT_DATE_OF_INCORPORATION_YY.value=data_vec[42];");
			out.println("    	document.Form1.TXT_VAT_REG_NO.value=data_vec[43];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_DD.value=data_vec[44];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_MM.value=data_vec[45];");
			out.println("    	document.Form1.TXT_VAT_REG_DATE_YY.value=data_vec[46];");
			out.println("    	document.Form1.TXT_WITH_HOLDING_TAX.value=data_vec[47];");
			out.println("    	}");
			out.println("    	else{");
			out.println("    	document.Form1.TXT_CLIENT_TITLE.value=data_vec[50];");
			out.println("    	document.Form1.TXT_CLIENT_FNAME.value=data_vec[51];");
			out.println("    	document.Form1.TXT_CLIENT_SNAME.value=data_vec[52];");
			out.println("    	document.Form1.TXT_CLIENT_INITIALS.value=data_vec[53];");
			out.println("    	document.Form1.TXT_CLIENT_ONAME.value=data_vec[54];");
			out.println("    	document.Form1.TXT_CLIENT_IDNO.value=data_vec[48];");
			out.println("    	document.Form1.TXT_CLIENT_PASSPORT.value=data_vec[49];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_DD.value=data_vec[55];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_MM.value=data_vec[56];");
			out.println("    	document.Form1.TXT_DATE_OF_BIRTH_YY.value=data_vec[57];");
			out.println("    	document.Form1.TXT_GENDER.value=data_vec[58];");
			out.println("    	}");
			out.println("    	document.Form1.TXT_CLIENT_GROUP.value=data_vec[6];");
			out.println("    	document.Form1.TXT_CLIENT_CRIB.value=data_vec[7];");
			out.println("			enable_comment(document.Form1.TXT_CLIENT_CRIB.value)");
			out.println("    	document.Form1.TXT_CLIENT_CRIB_COMMENT.value=data_vec[8];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_STATUS.value=data_vec[9];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_ADDRESS1.value=data_vec[10];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_TELEPHONE.value=data_vec[15];");
			out.println("    	document.Form1.TXT_CLIENT_HOME_ADDRESS2.value=data_vec[11];");
			out.println("    	document.Form1.TXT_CLIENT_OFFICE_TELEPHONE.value=data_vec[16];");
			out.println("    	document.Form1.TXT_CLIENT_CITY.value=data_vec[12];");
			out.println("    	document.Form1.TXT_CLIENT_FAXNO.value=data_vec[17];");
			out.println("    	document.Form1.TXT_CLIENT_COLLECTION_AREA.value=data_vec[13];");
			out.println("    	document.Form1.TXT_CLIENT_MOBILE.value=data_vec[19];");
			out.println("    	document.Form1.TXT_CLIENT_REFERENCE.value=data_vec[14];");
			out.println("    	document.Form1.TXT_CLIENT_EMAIL.value=data_vec[18];");
			out.println("    	document.Form1.TXT_CLIENT_KEY_DECISION_MAKER.value=data_vec[20];");
			out.println("    	document.Form1.TXT_CLIENT_CONT_PERSON.value=data_vec[21];");
			out.println("    	document.Form1.TXT_CLIENT_DESIG_PAYMENT.value=data_vec[22];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_STATUS.value=data_vec[23];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_ADDRESS1.value=data_vec[24];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_TELEPHONE.value=data_vec[27];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_ADDRESS2.value=data_vec[25];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_FAX.value=data_vec[28];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_EMAIL.value=data_vec[29];");
			out.println("    	document.Form1.TXT_CLIENT_FACTORY_CONPERSON.value=data_vec[26];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_STATUS.value=data_vec[30];");
			out.println("    	document.Form1.TXT_CORESSS_HOMEADDRESS1.value=data_vec[31];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_TELEPHONE.value=data_vec[34];");
			out.println("    	document.Form1.TXT_CORESSS_HOMEADDRESS2.value=data_vec[32];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_FAX.value=data_vec[35];");
			out.println("    	document.Form1.TXT_CORESSS_CITY.value=data_vec[33];");
			out.println("    	document.Form1.TXT_CLIENT_CORESSS_EMAIL.value=data_vec[36];");
			//out.println("  		makeRequest(21);");
			out.println("		}");
			out.println("		if(document.Form1.hid_display_client.value==\"30\" && document.Form1.TXT_CLIENT_CODE.value!=''){");			
			out.println("  		document.Form1.hid_display_client.value=99;");
			out.println("  		if(data_vec.length>0){");
			out.println("  			alert('Client code already exist with client code:'+data_vec[0]+' and name:'+data_vec[1]+' as a '+data_vec[2]+' \\nplease select edit option to modify record');");
			out.println("  			help_update();");
			out.println("  		}");
			out.println("  		else{");
			out.println("				//document.Form1.TXT_CLIENT_CODE.value=\"\";");			
			out.println("  			//help_update();");
			out.println("  		}");
			out.println("		}");
			out.println("		else if(document.Form1.hid_display_client.value==\"31\"){");
			out.println("  		document.Form1.hid_display_client.value=99;");
			out.println("  		if(data_vec.length>0){");
			out.println("  			alert('Client name already exist with client code:'+data_vec[0]+' and name:'+data_vec[1]+' as a '+data_vec[2]+' \\nplease select edit option to modify record');");
			out.println("  			help_update();");
			out.println("  		}");
			out.println("  		else{");
			out.println("  		}");
			out.println("		}");
			out.println("		else if(data_vec.length>0  && document.Form1.hid_display_client.value == '911'){");
			out.println("			alert('NIC No already exists');");
			out.println("     document.Form1.TXT_CLIENT_IDNO.value=''; ");
			out.println("     document.Form1.TXT_CLIENT_IDNO.focus(); ");
			out.println("		}");
			out.println("		else if(data_vec.length>0  && document.Form1.hid_display_client.value == '912'){");
			out.println("			alert('Business Reg. No already exists');");
			out.println("     document.Form1.TXT_BUSINESS_CERTIFICATE_NO.value=''; ");
			out.println("     document.Form1.TXT_BUSINESS_CERTIFICATE_NO.focus(); ");
			out.println("		}");
			out.println("}");
			
			
			out.println("function check_client_code(){");
			out.println("		makeRequest(30);"); 
			out.println("}"); 
			
			out.println("function check_client_name(){");
			out.println("		makeRequest(31);"); 
			out.println("}"); 
			
			out.println("function makeRequest_nic(obj) {");
			out.println("   document.Form1.hid_display_client.value='911';");
			out.println("   if(document.Form1.SCREEN_NAME.value=='NEW' && document.Form1.TXT_CLIENT_IDNO.value!='') {");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_NIC&nic_no=\"+obj.value;");
			out.println("		load_interface(m_url,'XML'); ");
			out.println("		}");
			out.println("   else if(document.Form1.SCREEN_NAME.value=='EDIT' && document.Form1.TXT_CLIENT_IDNO.value!='') {");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_NIC_EDIT&nic_no=\"+obj.value+\"&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			out.println("		load_interface(m_url,'XML'); ");
			out.println("		}");
			out.println("}");
			
			out.println("function makeRequest_business_cert_no(obj) {");
			out.println("   document.Form1.hid_display_client.value='912';");
			out.println("   if(document.Form1.SCREEN_NAME.value=='NEW' && document.Form1.TXT_BUSINESS_CERTIFICATE_NO.value!='') {");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_BUSINESS_CERTIFICATE_NO&business_no=\"+obj.value;");
			out.println("		load_interface(m_url,'XML'); ");
			out.println("		}");
			out.println("   else if(document.Form1.SCREEN_NAME.value=='EDIT' && document.Form1.TXT_BUSINESS_CERTIFICATE_NO.value!='') {");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_BUSINESS_CERTIFICATE_NO_EDIT&business_no=\"+obj.value+\"&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			out.println("		load_interface(m_url,'XML'); ");
			out.println("		}");
			out.println("}");
			
			out.println("function makeRequest(m_val) {");
			out.println("		obj=document.Form1.TXT_CLIENT_CODE.value;");
			out.println("		if(m_val==\"1\"){");
			out.println("			document.Form1.hid_display_client.value=1;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"2\"){");
			out.println("			document.Form1.hid_display_client.value=2;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_DEBTOR_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"3\"){");
			out.println("			document.Form1.hid_display_client.value=3;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_DIRECTOR_DETAILS&client_code=\"+obj;");
			out.println("		}");
			//Added by Mahela on 13-12-2006
			out.println("		else if(m_val==\"4\"){");
			out.println("			document.Form1.hid_display_client.value=4;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_GUARANTOR_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"5\"){");
			out.println("			document.Form1.hid_display_client.value=5;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_SUBSIDIA_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"6\"){");
			out.println("			document.Form1.hid_display_client.value=6;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_BANK_ACC_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"7\"){");
			out.println("			document.Form1.hid_display_client.value=7;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_AUDITOR_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"8\"){");
			out.println("			document.Form1.hid_display_client.value=8;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_CREDIT_FACILITY_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"9\"){");
			out.println("			document.Form1.hid_display_client.value=9;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_PROP_SECURITY_DETAILS&client_code=\"+obj;");
			out.println("		}");
			//End of Addition
			out.println("		else if(m_val==\"10\"){");
			out.println("			document.Form1.hid_display_client.value=10;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_SUPPLIER_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"11\"){");
			out.println("			document.Form1.hid_display_client.value=11;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_PRODUCT_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"12\"){");
			out.println("			document.Form1.hid_display_client.value=12;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_TOP_DEBTORS_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"32\"){");
			out.println("			document.Form1.hid_display_client.value=32;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_INQUERY&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			out.println("		}");
			///-----------------leasing data loading
			out.println("		if(m_val==\"20\"){");
			out.println("			document.Form1.hid_display_client.value=20;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_DETAILS_LEASING&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"21\"){");
			out.println("			document.Form1.hid_display_client.value=21;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_DIRECTOR_DETAILS_LEASING&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"22\"){");
			out.println("			document.Form1.hid_display_client.value=22;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_BANK_ACC_DETAILS_LEASING&client_code=\"+obj;");
			out.println("		}");
			out.println("		else if(m_val==\"23\"){");
			out.println("			document.Form1.hid_display_client.value=23;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_SUPPLIER_DETAILS_LEASING&client_code=\"+obj;");
			out.println("		}");
			//check for exsisting clients
			out.println("		if(m_val==\"30\"){");
			out.println("			document.Form1.hid_display_client.value=30;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_CODE&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			out.println("		}");
			out.println("		else if(m_val==\"31\"){");
			out.println("			document.Form1.hid_display_client.value=31;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_CHECK_CLIENT_NAME&client_code=\"+document.Form1.TXT_CLIENT_FULL_NAME.value;");
			out.println("		}");
			///-----------------lost the event focus
			out.println("		else if(m_val==\"99\"){");//set dummy value
			out.println("			document.Form1.hid_display_client.value=99;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MAS_sql_validations?chksql=m_EDIT_CLIENT_TOP_DEBTORS_DETAILS&client_code=\"+obj;");
			out.println("		}");
			out.println("		load_interface(m_url,'XML');");
			out.println("}");	
			
			out.println("function assign_codes(){ ");
			out.println("document.Form1.hid_FACILITY_NO.value = '"+m_facility_no+"';");
			out.println("document.Form1.hid_CLIENT_CODE.value = '"+m_client_code+"';");
			out.println("}"); 

			out.println("function load_help_msg() {"); 
			out.println("    m_help_message = \"m_help_msg_LAKDL_FA_CR_CLIENT_CREATION\";"); 
			out.println("    HelpBox_msg(m_help_message);"); 
			out.println("}"); 
			
			out.println("function HelpBox_msg(m_help_message) {"); 
			out.println("		popupwin = window.showModalDialog(servlet_client_url+\":\"+client_t3_port+\"/\"+client_name+\"AF_MAS_Help_Msg_Servlet?class_in=\"+client_name+\"FA_MAS_Help_Msg_select\"+"); 
			out.println("  \"&help_message_in=\"+m_help_message);"); 
			out.println("}"); 
			
			out.println("function help_update_value_assign_99() {"); 
			out.println("	if(document.Form1.SCREEN_NAME.value==\"NEW\"){ ");
			out.println("		if(oBj.valout[3]=='INDIVIDUAL') {");
			out.println("		document.Form1.TXT_CLIENT_TYPE.value='I';"); 
			out.println("		}");
			out.println("		else {");
			out.println("		document.Form1.TXT_CLIENT_TYPE.value='C';"); 
			out.println("		}");
			out.println("		document.Form1.TXT_CLIENT_RELATIONSHIP.value='D';"); 
			out.println("		document.Form1.TXT_CLIENT_CODE.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_CLIENT_FULL_NAME.value=oBj.valout[5];"); 
			out.println("   load_data_sections();");
			out.println("		if(oBj.valout[7]==\"LEASING\"){"); 
			out.println("			m_str_data='Records loaded from leasing division from client '+oBj.valout[2]+' with the active status '+oBj.valout[6]+' ?';");
			out.println("			if(confirm(m_str_data)){");
			out.println("   		makeRequest(20);");
			out.println("   	}");
			out.println("			else{");
			out.println("				clear_data();");
			out.println("			}");
			out.println("   }");
			out.println("   else{");
			out.println("   	makeRequest(1);");
			out.println("   }");
			out.println("	}"); 
			out.println("	else{");
			out.println("		clear_data();");
			out.println("	}");
			out.println("}"); 
			
			
			out.println("function get_vector_normal(m_data){");
			out.println("		product_feature_details.innerHTML=m_data;");
			out.println("}");
			
			out.println("function clear_data(){"); 
			out.println("  document.Form1.TXT_CLIENT_CODE.value=\"\";"); 
			out.println("  document.Form1.TXT_CLIENT_FULL_NAME.value=\"\";"); 
			out.println("  load_data_sections();");
			out.println("}");

			out.println("function check_exist_nic(obj){");
			out.println("	if(parseInt(document.Form1.hid_director_count.value)>0){  "); 
			out.println("		for(var i=1;i<=parseInt(document.Form1.hid_director_count.value);i++){");
			out.println("    		obj1=document.Form1.elements[\"TXT_DIRECTOR_NAME_\"+i];");
			out.println("    		obj2=document.Form1.elements[\"TXT_DIRECTOR_NIC_\"+i];");
			out.println("				if(obj1.value==\"\" && obj2.value!=\"\" ){");
			out.println("					alert('Director Name cannot be Empty');"); 
			out.println("					obj1.focus();"); 
			out.println("					m_submit=false;"); 
			out.println("				}"); 
			out.println("			  if(obj2.value!=\"\" && val_nic1(obj2) ){");
			out.println("				 makeRequest1(obj1,obj2);");
			out.println("				 if(document.Form1.hid_nic_status.value==1) {");
			out.println("				 	obj.value='';");
			out.println("				 	obj.focus();");
			out.println("					}"); 
			out.println("				}"); 
			out.println("		}"); 
			out.println("	}"); 
			out.println("}"); 

			out.println("function validate_data(){"); 
			out.println("	//validations goes here"); 
			out.println("	m_submit=true;"); 
			out.println("	if(document.Form1.TXT_CLIENT_CODE.value==\"\" && document.Form1.SCREEN_NAME.value==\"EDIT\"){  "); 
			out.println("		DIV_TXT_CLIENT_CODE.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}"); 
			out.println("	else if(document.Form1.TXT_CLIENT_FULL_NAME.value==\"\"){  "); 
			out.println("		DIV_TXT_CLIENT_FULL_NAME.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}"); 
			out.println("	else if(document.Form1.TXT_CLIENT_COLLECTION_AREA.value==\"\"){  "); 
			out.println("		DIV_TXT_COLLECTION_AREA.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CLIENT_HOME_ADDRESS1.value==\"\"){  "); 
			out.println("		DIV_TXT_CLIENT_HOME_ADDRESS1.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CLIENT_CONT_PERSON.value==\"\"){  "); 
			out.println("		DIV_TXT_CLIENT_CONT_PERSON.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CLIENT_CRIB.value==\"IRREGULAR\" && document.Form1.TXT_CLIENT_CRIB_COMMENT.value==\"\" ){  "); 
			out.println("		comment.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_3RD_PARTY_STATUS.value==\"Y\" && document.Form1.TXT_3RD_PARTY_DEBTOR_DET.value==\"\" ){  "); 
			out.println("		specify.style.color='red';");
			out.println("		m_submit=false;"); 
			out.println("		alert('Please enter all required fields marked with a * on screen');"); 
			out.println("	}");
			/*out.println("	if(m_submit) { ");
			out.println("	 if(document.Form1.TXT_CLIENT_TYPE.value==\"I\"  ){ ");
			out.println("   if(document.Form1.TXT_CLIENT_IDNO.value==\"\" ){  "); 
			out.println("			DIV_TXT_CLIENT_IDNO.style.color='red';");
			out.println("			alert(\"Please enter all required fields marked with a '*' on screen.\"); ");
			out.println("			m_submit=false;"); 
			out.println("		}");
			out.println("		else if(document.Form1.TXT_DATE_OF_BIRTH_DD.value==\"\" || document.Form1.TXT_DATE_OF_BIRTH_MM.value==\"\" || document.Form1.TXT_DATE_OF_BIRTH_YY.value==\"\") {");
			out.println("			DIV_TXT_CLIENT_DOB.style.color='red';");
			out.println("			alert(\"Please enter all required fields marked with a '*' on screen.\"); ");
			out.println("			m_submit=false;"); 
			out.println("		}");
			out.println("	  else if(!validate_NIC(document.Form1.TXT_CLIENT_IDNO)){	");
			out.println("			m_submit=false;"); 
			out.println("		}");
			out.println("	 }");
			out.println("	}");*/
			out.println("	if(m_submit){");
			out.println("		return true;");
			out.println("	}else{"); 			
			out.println("		return false;");
			out.println("	}");
			out.println("	}");
			
			out.println("function assignState(val){");
			out.println("	document.Form1.hid_chk_status.value=val;");
			out.println("}");

			out.println("function before_submit(){ "); 
			out.println("	get_display_msg();");
			out.println("	assign_codes();");
			out.println("	if(validate_data()){"); 
			out.println("		if(confirm(\"Are you sure you want to \"+m_sav_msg+\" ?\")){ ");
			out.println("			for (var i=0; i < document.Form1.elements.length; i++ ) {");
			out.println("				document.Form1.elements[i].disabled=false;");
			out.println("			}");
			out.println("			if(validate_data()){"); 
			out.println("				document.Form1.action='"+m_class_url+"/"+m_fschema_name+"FA_OP_save_debtor_creation';");  
			out.println("				document.Form1.submit();	"); 
			out.println("			}"); 
			out.println("		}"); 
			out.println("	}"); 
			out.println("} "); 

			out.println("function load_lock(){	"); 
			out.println("//document.oncontextmenu=new Function(\"return false\");"); 
			out.println("}	"); 

			out.println("function clear_window(){	"); 
			out.println("		if(confirm(\"Are you sure you want to clear the screen ?\")){ "); 
			out.println("		window.location.href='"+m_class_url+"/"+m_fschema_name+"FA_OP_display_debtor_creation';"); 
			out.println("		}"); 
			out.println("}"); 
			
			out.println("function new_window(){	"); 
			out.println("	window.location.href='"+m_class_url+"/"+m_fschema_name+"FA_OP_display_debtor_creation';"); 
			out.println("}"); 

			out.println("function save_window(){	"); 
			out.println("	before_submit();"); 
			out.println("}"); 

			out.println("function load_roll_value(m_val){"); 
			out.println("	help_box.innerHTML=\" Operation Process - Debtor Creation  - \"+m_val;"); 
			out.println("}"); 

			out.println("function load_roll_out_value(){");
			out.println("	help_box.innerHTML=\" Operation Process - Debtor Creation  - \"+document.Form1.hid_status.value;"); 
			out.println("}"); 
			
			out.println("function load_screen_status(m_val){"); 
			out.println("		if(m_val==\"NEW\"){"); 
			out.println("			new_window();"); 
			out.println("			document.Form1.BUT_HELP_MAIN.disabled=true;");
			out.println("			document.Form1.TXT_CLIENT_CODE.disabled=true;"); 
			out.println("		}"); 
			out.println("		if(m_val==\"HELP\"){"); 
			out.println("			load_help_msg();"); 
			out.println("		}"); 
			out.println("		else if(m_val!=\"EDIT\"){"); 
			out.println("			document.Form1.BUT_HELP_MAIN.disabled=false;"); 
			out.println("			document.Form1.TXT_CLIENT_CODE.disabled=false;"); 
			out.println("			document.Form1.TXT_CLIENT_FULL_NAME.disabled=true;"); 
			out.println("		}"); 
			out.println("		else{");
			out.println("			document.Form1.BUT_HELP_MAIN.disabled=false;");
			out.println("			document.Form1.TXT_CLIENT_CODE.disabled=false;"); 
			out.println("		}"); 
			out.println("		document.Form1.SCREEN_NAME.value=m_val;"); 
			out.println("		if(m_val==\"NEW\"){");
			out.println("			document.Form1.hid_status.value=\"New\";"); 
			out.println("		}");
			out.println("		else if(m_val==\"EDIT\"){");  
			out.println("			document.Form1.hid_status.value=\"Edit\";");  
			out.println("		}");
			out.println("		else{");  
			out.println("			document.Form1.hid_status.value=\"\";");  
			out.println("		}"); 
			out.println("}"); 
			
			out.println("function get_display_msg(){"); 
			out.println("	if(document.Form1.SCREEN_NAME.value==\"NEW\"){");
			out.println("		m_sav_msg=\"Save\";"); 
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"EDIT\"){");  
			out.println("		m_sav_msg=\"Modify\";");  
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"DACT\"){");  
			out.println("		m_sav_msg=\"Deactivate\";");  
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"RACT\"){");  
			out.println("		m_sav_msg=\"Reactivate\";");  
			out.println("	}");
			out.println("	else{");  
			out.println("		m_sav_msg=\"\";");  
			out.println("	}"); 
			out.println("}"); 

			out.println("function MyDialog(){"); 
			out.println("	this.valout   = new Array(10);"); 
			out.println("}"); 

			out.println("function HelpBox(Start,End,Hid_No,Max) {"); 
			out.println("    oBj = new MyDialog();"); 
			out.println("    oBj.valout[1]  = \" \";"); 
			out.println("    oBj.valout[2]  = \" \";"); 
			out.println("    oBj.valout[3]  = \" \";"); 
			out.println("	"); 
			out.println("	popupwin = window.showModalDialog(servlet_client_url+\":\"+client_t3_port+\"/\"+client_name+\"FA_MAS_Help_Servlet?class_in=\"+client_name+\"FA_MAS_help_select_client\"+"); 
			out.println("    \"&Sql_in=\"+m_sql+\"&Start_in=\"+Start+"); 
			out.println("    \"&End_in=\"+End+\"&Crit_In=\"+m_criteria+"); 
			out.println("    \"&Hid_No=\"+Hid_No, oBj,\"dialogWidth:25em; dialogHeight:18em; center:yes; status:no\");"); 
			out.println("	"); 
			out.println("	if(oBj.valout[1] !=\" \"){"); 
			out.println("		if(oBj.valout[1] !=\"Close\"){"); 
			out.println("			if(oBj.valout[1]!=\"Prev\"){"); 
			out.println("				if(oBj.valout[1]!=\"Next\"){"); 
			out.println("					if(document.Form1.hid_help_type.value==\"99\"){"); //MAIN
			out.println("						help_update_value_assign_99();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"10\"){"); 
			out.println("						help_update_value_assign_10();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"11\"){"); 
			out.println("						help_update_value_assign_11();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"12\"){"); 
			out.println("						help_update_value_assign_12();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"14\"){"); 
			out.println("						help_update_value_assign_14();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"15\"){"); 
			out.println("						help_update_value_assign_15();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"16\"){"); 
			out.println("						help_update_value_assign_16();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"17\"){"); 
			out.println("						help_update_value_assign_17();"); 
	  	out.println("					}"); 
			out.println("					if(document.Form1.hid_help_type.value==\"18\"){"); 
			out.println("						help_update_value_assign_18();"); 
	  	out.println("					}");
			out.println("					if(document.Form1.hid_help_type.value==\"19\"){"); 
			out.println("						help_update_value_assign_19();"); 
	  	out.println("					}");
			out.println("					if(document.Form1.hid_help_type.value==\"20\"){"); 
			out.println("						help_update_value_assign_20();"); 
	  	out.println("					}");
			out.println("				}"); 
			out.println("				else{"); 
			out.println("					Next(oBj.valout[2],oBj.valout[3],Hid_No);"); 
			out.println("					return false;"); 
			out.println("				} "); 
			out.println("			}"); 
			out.println("			else{	"); 
			out.println("				Prev(oBj.valout[2],oBj.valout[3],Hid_No);"); 
			out.println("			}	"); 
			out.println("	 	}"); 
			out.println("	 	else{	"); 
			out.println("	 	}	"); 
			out.println("	}"); 
			out.println("	else{	"); 
			out.println("	}");
			out.println("}"); 

			out.println("function Prev(Start,End,Hid_No){"); 
			out.println("		HelpBox(Start,End,Hid_No);"); 
			out.println("}"); 

			out.println("function Next (Start,End,Hid_No){"); 
			out.println("		HelpBox(Start,End,Hid_No);"); 
			out.println("}"); 
			
			
			
			out.println("function help_update_value_assign_10() {"); 
			out.println("		document.Form1.TXT_CLIENT_LEGAL_ST_BUSINESS.value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_11() {"); 
			out.println("		document.Form1.TXT_CLIENT_GROUP.value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_12() {"); 
			out.println("		document.Form1.TXT_CLIENT_CITY.value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_19() {"); 
			out.println("		document.Form1.TXT_CORESSS_CITY.value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_14() {"); 
			out.println("		document.Form1.TXT_CLIENT_COLLECTION_AREA.value=oBj.valout[2];"); 
			out.println("}");
		
			out.println("function help_update_value_assign_15() {"); 
			out.println(" 	m_num=document.Form1.hid_f_count.value;");
			out.println("		document.Form1.elements[\"TXT_BANK_NAME_\"+m_num].value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_16() {"); 
			out.println(" 	m_num=document.Form1.hid_f_count.value;");
			out.println("		document.Form1.elements[\"TXT_BANK_NAME_\"+m_num].value=oBj.valout[4];");
			out.println("		document.Form1.elements[\"TXT_BANK_BRANCH_\"+m_num].value=oBj.valout[2];");
			out.println("}");
	
			out.println("function help_update_value_assign_17() {"); 
			out.println("		document.Form1.TXT_EXPOSURE_CAT.value=oBj.valout[2];"); 
			out.println("}");
			
			out.println("function help_update_value_assign_18() {"); 
			out.println("		document.Form1.TXT_EXPOSURE_SECTOR.value=oBj.valout[2];"); 
			out.println("}");
		
			out.println("function help_update_value_assign_20() {"); 
			out.println(" 	m_num=document.Form1.hid_f_count.value;");
			out.println("		document.Form1.elements[\"TXT_PRODUCT_SUB_SECTOR_\"+m_num].value=oBj.valout[2];");
			out.println("}");
			
			out.println("function help_update_legal_code() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"10\";"); 
			out.println("		m_sql = \"m_help_DIV_CLIENT_LEGAL_ST_BUSINESS_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_CLIENT_LEGAL_ST_BUSINESS.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_client_group() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"11\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_GROUP_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_CLIENT_GROUP.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_city_code() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"12\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_CITY_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_CLIENT_CITY.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_city_code_2() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"19\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_CITY_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_CORESSS_CITY.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_collection_location_code() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"14\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_COLLECTION_AREA_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_CLIENT_COLLECTION_AREA.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function update_bank_code(m_num) {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"15\";"); 
			out.println(" 	document.Form1.hid_f_count.value=m_num;");
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_BANK_sql\";"); 
			out.println("  	m_val = document.Form1.elements[\"TXT_BANK_NAME_\"+m_num].value;"); 
			out.println("  	m_criteria = m_val+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}");

			out.println("function update_product_sub_sector_code(m_num) {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"20\";"); 
			out.println(" 	document.Form1.hid_f_count.value=m_num;");
			out.println("		m_sql = \"m_help_DIV_TXT_PRODUCT_SUB_SECTOR_sql\";"); 
			out.println("  	m_val = document.Form1.elements[\"TXT_PRODUCT_SUB_SECTOR_\"+m_num].value;"); 
			out.println("  	m_criteria = m_val+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}");
			
			out.println("function update_branch_accounts(m_num) {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"16\";"); 
			out.println(" 	document.Form1.hid_f_count.value=m_num;");
			out.println("		m_sql = \"m_help_DIV_TXT_CLIENT_BRANCH_sql\";"); 
			out.println("  	m_val1 = document.Form1.elements[\"TXT_BANK_NAME_\"+m_num].value;"); 
			out.println("  	m_val2 = document.Form1.elements[\"TXT_BANK_BRANCH_\"+m_num].value;"); 
			out.println("  	m_criteria = m_val2+\"@\"+m_val1+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}");
			
			out.println("function help_update_exposure_code() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"17\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_EXPOSURE_CAT_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_EXPOSURE_CAT.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_sector_code() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"18\";"); 
			out.println("		m_sql = \"m_help_DIV_TXT_EXPOSURE_SECTOR_sql\";"); 
			out.println("  	m_criteria = document.Form1.TXT_EXPOSURE_SECTOR.value+\"@\";"); 
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update() {"); 
			out.println(" document.Form1.hid_help_type.value=\"99\";"); 
			out.println(" m_sql = \"m_help_DIV_TXT_FACTOR_CLIENT_CODE_sql\";"); 
			out.println(" m_criteria = document.Form1.TXT_CLIENT_CODE.value+\"@\";"); 
			out.println(" HelpBox('1','10','0');"); 
			out.println("}"); 

			
			out.println("function load_data_sections() {");
			out.println("	if(document.Form1.TXT_CLIENT_TYPE.value==\"I\"){ ");
			out.println("	   client_general_data.innerHTML='<table  width=\"100%\">'+ ");
			out.println("	   '<tr >'+");
			out.println("	   '<td width=\"20%\">Title </td>'+");
			out.println("	   '<td width=\"25%\" ><select name=\"TXT_CLIENT_TITLE\" class=\"txt_input\">'+");
			out.println("	   '<OPTION value=\"MR\" SELECTED >Mr </option>'+");
			out.println("	   '<OPTION value=\"MRS\" >Mrs </option>'+");
			out.println("	   '<OPTION value=\"MISS\" >Miss </option>'+");
			out.println("	   '<OPTION value=\"DR\" >Dr </option>'+");
			out.println("	   '<OPTION value=\"REV\" >Rev </option>'+");
			out.println("	   '<OPTION value=\"PROF\" >Prof </option>'+");
			out.println("	   '</select></td>'+");
			out.println("	   '<td width=\"5%\"></td>'+ ");
			out.println("	   '<td width=\"20%\" ></td>'+");
			out.println("	   '<td width=\"25%\" ></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+");
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+ ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_FNAME\"  class=div_input>First Name </DIV></td>'+ ");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_FNAME\" maxlength=\"200\" size=\"50\" style=\"width:200\"></td>'+ ");
			out.println("	   '<td width=\"5%\"></td>'+  ");
			out.println("	   '<td width=\"20%\" ></td>'+");
			out.println("	   '<td width=\"25%\" ></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+ ");
			out.println("	   '</tr>'+	");
			out.println("	   '<tr >'+ ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_SNAME\"  class=div_input>Surname </DIV></td>'+ ");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_SNAME\" maxlength=\"50\" size=\"50\" style=\"width:200\"></td>'+  ");
			out.println("	   '<td width=\"5%\"></td>'+ ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_INITIALS\"  class=div_input>Initials </DIV></td>'+ ");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_INITIALS\" maxlength=\"20\" size=\"50\" style=\"width:200\"></td>'+ ");
			out.println("	   '<td width=\"*%\"></td>'+  ");
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+ ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_ONAME\"  class=div_input>Other Names </DIV></td>'+ ");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_ONAME\" maxlength=\"200\" size=\"200\" style=\"width:200\"></td>'+ ");
			out.println("	   '<td width=\"5%\"></td>'+  ");
			out.println("	   '<td width=\"20%\" ></td>'+");
			out.println("	   '<td width=\"25%\" ></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+   ");
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+ ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_IDNO\"  class=div_input>NIC No. *</DIV></td>'+ ");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_IDNO\" maxlength=\"10\" size=\"50\" style=\"width:200\"  onblur=\"makeRequest_nic(this)\"></td>'+ ");
			out.println("	   '<td width=\"5%\"></td>'+  ");
			out.println("	   '<td width=\"20%\" ><DIV id=\"DIV_TXT_CLIENT_IDNOpas\"  class=div_input>Passport No. </DIV></td>'+");
			out.println("	   '<td width=\"25%\" ><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_PASSPORT\" maxlength=\"15\" size=\"50\" style=\"width:200\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+ ");
			out.println("	   '</tr>'+	");
			out.println("	   '<tr >'+ ");
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_CLIENT_DOB\"  class=div_input>Date of Birth *</DIV></td>'+ ");
			out.println("	   '<td width=\"25%\"><input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_BIRTH_DD\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_BIRTH_MM\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_BIRTH_YY\" maxlength=\"4\" size=\"4\" onblur=\"checkMonthLength(document.Form1.TXT_DATE_OF_BIRTH_DD,document.Form1.TXT_DATE_OF_BIRTH_MM,document.Form1.TXT_DATE_OF_BIRTH_YY)\"><a href style=\"{cursor:hand; }\" onclick=load_calendar(\"dob\")>   Calendar</a></td>'+ ");
			out.println("	   '<td width=\"5%\"></td>'+  ");
			out.println("	   '<td width=\"15%\">Gender</td>'+");
			out.println("	   '<td width=\"25%\"><select name=\"TXT_GENDER\" class=\"txt_input\" >'+");
			out.println("	   '<OPTION value=\"M\" SELECTED >Male </option>'+");
			out.println("	   '<OPTION value=\"F\" >Female </option>'+");
			out.println("	   '</SELECT></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+ ");
			out.println("	   '</tr>'+");
			out.println("	   '</table>'+ ");
			out.println("		 '<div  id=\"add_directors_data\"  class=div_input></DIV>';"); 
			out.println("		 document.Form1.hid_director_count.value=0;");
			out.println("		 add_directors_data.innerHTML=\"\";"); 
			out.println("	}");
			out.println("	else{");
			out.println("	   client_general_data.innerHTML='<table width=\"100%\">'+"); 
			out.println("	   '<tr>'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_CLIENT_LEGAL_ST_BUSINESS\"  class=div_input>Legal Status of Business </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_LEGAL_ST_BUSINESS\" maxlength=\"10\" size=\"50\" style=\"width:100\" >'+");
			out.println("	   '<input class=\"but_input\" type=\"button\" name=\"BUT_HELP_LEGAL_ENTITY\" value=\"Help\" onClick=\"help_update_legal_code()\"></td>'+"); 
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");	
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_CLIENT_ISSUED_SHARE_CAPITAL\"  class=div_input>Issued Share Capital  (Rs.)</DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_ISSUED_SHARE_CAPITAL\" maxlength=\"20\" size=\"50\" style=\"width:200\" onblur=\"format_num(this,2)\"></td>'+"); 
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_BUSINESS_CERTIFICATE_NO\"  class=div_input>Business Certificate No </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_BUSINESS_CERTIFICATE_NO\" maxlength=\"15\" size=\"50\" style=\"width:200\" onblur=\"makeRequest_business_cert_no(this)\"></td>'+"); 
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_DATE_OF_INCORPORATION\"  class=div_input>Date Of Incorporation </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_INCORPORATION_DD\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_INCORPORATION_MM\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_DATE_OF_INCORPORATION_YY\" maxlength=\"4\" size=\"4\" onblur=\"checkMonthLength(document.Form1.TXT_DATE_OF_INCORPORATION_DD,document.Form1.TXT_DATE_OF_INCORPORATION_MM,document.Form1.TXT_DATE_OF_INCORPORATION_YY)\"> <a href style=\"{cursor:hand; }\" onclick=load_calendar(\"doi\")>   Calendar</a></TD>'+");
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_VAT_REG_NO\"  class=div_input>VAT Registration No </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_VAT_REG_NO\" maxlength=\"15\" size=\"50\" style=\"width:200\"></td>'+"); 
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_VAT_REG_DATE\"  class=div_input>Date Of VAT Registration  </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><input class=\"txt_input5\" type=\"text\" name=\"TXT_VAT_REG_DATE_DD\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_VAT_REG_DATE_MM\" maxlength=\"2\" size=\"2\" >'+");
			out.println("	   '<input class=\"txt_input5\" type=\"text\" name=\"TXT_VAT_REG_DATE_YY\" maxlength=\"4\" size=\"4\" onblur=\"checkMonthLength(document.Form1.TXT_VAT_REG_DATE_DD,document.Form1.TXT_VAT_REG_DATE_MM,document.Form1.TXT_VAT_REG_DATE_YY)\"> <a href style=\"{cursor:hand; }\" onclick=load_calendar(\"dov\")>   Calendar</a> </TD>'+");
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '<tr >'+"); 
			out.println("	   '<td width=\"20%\"><DIV id=\"DIV_TXT_WITHHOLD_TAX_NO\"  class=div_input>With Holding TAX </DIV></td>'+"); 
			out.println("	   '<td width=\"25%\"><select name=\"TXT_WITH_HOLDING_TAX\" class=\"txt_input\">'+");
			out.println("    '<OPTION value=\"Y\" >Yes</option>'+");
			out.println("    '<OPTION value=\"N\" SELECTED>No</option></SELECT></td>'+");
			out.println("	   '<td width=\"5%\"></td>'+");  
			out.println("	   '<td width=\"20%\"></td>'+");
			out.println("	   '<td width=\"25%\"></td>'+");
			out.println("	   '<td width=\"*%\"></td>'+"); 
			out.println("	   '</tr>'+");
			out.println("	   '</table>'+"); 
			out.println("		 '<br>';"); 
			out.println("	}");
			out.println("}"); 		

			out.println("function load_calendar(num) {");
      out.println(" document.Form1.hid_cal_date.value=num;"); 
			out.println("	popupwin = window.open(servlet_client_url+\":\"+client_t3_port+\"/\"+client_name+\"CO_Calendar_Window\", \"oBj\",\"left=450,top=200,width=320,height=230\");"); 
			out.println("}");
			
			out.println("function load_c_date(val) {");
			out.println("  if(document.Form1.hid_cal_date.value=='doi'){"); 
			out.println("     v_dd = val.substr(0,val.indexOf('-'))");
			out.println("     if(v_dd.length <2) ");
			out.println("     v_dd = 0+v_dd ");
			out.println("     val = val.substr(val.indexOf('-')+1,val.length);");
			out.println("     v_mm = val.substr(0,val.indexOf('-')); ");
			out.println("     if(v_mm.length <2) ");
			out.println("     v_mm = 0+v_mm ");
			out.println("     v_yy = val.substr(val.indexOf('-')+1,val.length)");
			out.println("     document.Form1.TXT_DATE_OF_INCORPORATION_DD.value=v_dd;");
			out.println("     document.Form1.TXT_DATE_OF_INCORPORATION_MM.value=v_mm;");
			out.println("     document.Form1.TXT_DATE_OF_INCORPORATION_YY.value=v_yy;");
			out.println("  }");		
		  out.println("  else if(document.Form1.hid_cal_date.value=='dov'){"); 	
			out.println("     v_dd = val.substr(0,val.indexOf('-'))");
			out.println("     if(v_dd.length <2) ");
			out.println("     v_dd = 0+v_dd ");
			out.println("     val = val.substr(val.indexOf('-')+1,val.length);");
			out.println("     v_mm = val.substr(0,val.indexOf('-')); ");
			out.println("     if(v_mm.length <2) ");
			out.println("     v_mm = 0+v_mm ");
			out.println("     v_yy = val.substr(val.indexOf('-')+1,val.length)");
			out.println("     document.Form1.TXT_VAT_REG_DATE_DD.value=v_dd;");
			out.println("     document.Form1.TXT_VAT_REG_DATE_MM.value=v_mm;");
			out.println("     document.Form1.TXT_VAT_REG_DATE_YY.value=v_yy;");
			out.println("  }");		
			out.println("  else if(document.Form1.hid_cal_date.value=='dob'){"); 	
			out.println("     v_dd = val.substr(0,val.indexOf('-'))");
			out.println("     if(v_dd.length <2) ");
			out.println("     v_dd = 0+v_dd ");
			out.println("     val = val.substr(val.indexOf('-')+1,val.length);");
			out.println("     v_mm = val.substr(0,val.indexOf('-')); ");
			out.println("     if(v_mm.length <2) ");
			out.println("     v_mm = 0+v_mm ");
			out.println("     v_yy = val.substr(val.indexOf('-')+1,val.length)");
			out.println("     document.Form1.TXT_DATE_OF_BIRTH_DD.value=v_dd;");
			out.println("     document.Form1.TXT_DATE_OF_BIRTH_MM.value=v_mm;");
			out.println("     document.Form1.TXT_DATE_OF_BIRTH_YY.value=v_yy;");
			out.println("  }");		
			out.println("	 else {	");
			out.println(" 		m_count = parseInt(document.Form1.hid_cal_date.value)");
			out.println(" 		document.Form1.elements[\"TXT_BANK_FROMDATE_\"+m_count].value = val ");
			out.println("  }");		
			out.println("}");				

			out.println("function format_num_check(obj,size){");
			out.println("   if(obj.value != '' && isnumberok(obj,size) ) {");
		  out.println("   obj.value=format_noobject(obj.value); ");
			out.println("		}");
			out.println("		else if(obj.value != '') { ");
			out.println("   alert('Please enter a number ');");
			out.println("   obj.value='' ");
			out.println("   obj.focus(); ");
			out.println("		}");
			out.println("}");
			
			out.println("function num_check(obj,size){");
			out.println("   if(obj.value != '' && isnumberok(obj,size) ) {");
			out.println("		}");
			out.println("		else if(obj.value != '') { ");
			out.println("   alert('Please enter a number ');");
			out.println("   obj.value='' ");
			out.println("   obj.focus(); ");
			out.println("		}");
			out.println("}");

      out.println(" function enable_details_field(value){ ");
			out.println(" if(value == 'Y') { ");
			out.println("	  document.Form1.TXT_CREDIT_GRANTED_SECURE_DETAILS.disabled = false; ");
			out.println("  }"); 
			out.println("	else { ");
			out.println("	  document.Form1.TXT_CREDIT_GRANTED_SECURE_DETAILS.disabled = true; ");
			out.println("	  document.Form1.TXT_CREDIT_GRANTED_SECURE_DETAILS.value =''; ");
			out.println("  }"); 
			out.println(" }"); 
			
			out.println(" function enable_comment(value){ ");
			out.println("  if(value == 'IRREGULAR'){ ");
			out.println("	  comment.innerHTML = 'Comments *'; ");
			out.println("  }"); 
			out.println("  else { ");
			out.println("	  comment.innerHTML = 'Comments'; ");
			out.println("	  comment.style.color='black';");
			out.println("  }"); 
			out.println(" }"); 
			
			out.println(" function enable_specify(value){ ");
			out.println("  if(value == 'Y'){ ");
			out.println("	  specify.innerHTML = 'Specify *'; ");
			out.println("		document.Form1.TXT_3RD_PARTY_DEBTOR_DET.disabled= false");
			out.println("  }"); 
			out.println("  else { ");
			out.println("	  specify.innerHTML = 'Specify'; ");
			out.println("	  specify.style.color='black';");
			out.println("		document.Form1.TXT_3RD_PARTY_DEBTOR_DET.disabled= true");
			out.println("  }"); 
			out.println(" }"); 
			
			out.println("function client_detail_dispaly() {"); 
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_PRO_sql_validations_normal?chksql=CLIENT_NAME_SEARCH_HELP&full_name=\"+document.Form1.TXT_CLIENT_FULL_NAME.value;");
			out.println("		popupwin = window.showModalDialog(m_url,\"dialogWidth:600em; dialogHeight:100em; center:yes; status:no\");"); 
			out.println("}"); 
			
			out.println("</script>"); 
			out.println("<BODY class='body & txt-body' leftmargin='0' topmargin='0' marginwidth='0' ONLOAD=\"load_lock(),load_roll_value('New'),load_data_sections()\">"); 
			out.println("<FORM NAME='Form1' method='post'>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_cal_date' VALUE=\"\">");
			out.println("<input  type='hidden' value='NEW' name='SCREEN_NAME'> "); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_FACILITY_NO' VALUE=\"\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_CLIENT_CODE' VALUE=\"\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_help_type' VALUE=\"\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_help_status' VALUE=\"\">");
			out.println("<INPUT TYPE='Hidden' NAME='hid_status' VALUE=\"New\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_director_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_credit_facility_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_guarantor_count' VALUE=0>");
			out.println("<INPUT TYPE='Hidden' NAME='hid_associated_comp_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_auditor_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_security_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_bank_accounts_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_product_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_top_debtors_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_other_suppliers_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_f_count' VALUE=0>"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_display_client' VALUE=1"); 
			
			out.println("<table width='100%' class=table border='0' cellspacing='0' cellpadding='0'>"); 
			out.println("<tr>"); 
			//out.println("<td width='8' valign='top'><img src='spacer.gif' width='8' height='8'></td>"); 
			out.println("<td class='border_wht' valign='top'> "); 
			out.println("<table class='table' width='100%' border='0' cellspacing='0' cellpadding='0' height='100%'>"); 
			out.println("<tr> "); 
			out.println("<td height='30' class='pdn_mainHD'>"+m_header_name+"</td>"); 
			out.println("</tr>"); 
			out.println("<tr> "); 
			out.println("<td height='1'><img src='spacer.gif' width='1' height='1'></td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td style='height: 327px'>"); 
			out.println("<table class='table' border='0' cellpadding='0' cellspacing='0' height='100%' width='100%'>   "); 
			out.println("<tr>"); 
			out.println("<td height='1'><img height='1' src='spacer.gif' width='1' /></td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td align='left' class='pdn_txtpos2' style='height: 18px' id='help_box'> Operation Process - Debtor Creation </td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td  height='10px' class='pdn_txtpos'>"); 
			out.println("<table class='table' cellpadding='2' cellspacing='2' border='0'> "); 
			out.println("<tr><td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"New\");' onclick='load_screen_status(\"NEW\")' value=\"New\"></td>");  
			//out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Edit\");' onClick='load_screen_status(\"EDIT\")' value=\"Edit\"></td>");  
			out.println("<td width='6%'></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Save\");'  onClick='save_window()' value=\"Save\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Help\");' onClick='load_screen_status(\"HELP\")' value=\"Help\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Cancel\");'  onclick='clear_window()' value=\"Cancel\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Close\");'  onclick='window.close()' value=\"Close\"></td>"); 
			out.println("<td width='*%' align='right' class='div_input'></td></tr>");  
			out.println("</table>");  
			out.println("</td></tr><tr>");  
			out.println("<td class='line' height='1'><img height='1' src='spacer.gif' width='1' /></td>");  
			out.println("</tr><tr>");  
			out.println("<td class='pdn_txtpos' height='150' valign='top'>");  
			
			out.println("<br>");
			
			out.println("<table align='center' width='100%'>"); 
			out.println("<tr >"); 
			out.println("<td width='20%' >Client Type *</td>"); 
			out.println("<td width='*%' ><select name='TXT_CLIENT_TYPE' class='txt_input' onchange=\"load_data_sections()\">");
			out.println("<option value=\"C\" SELECTED>Corporate</option>");
			out.println("<option value=\"I\">Individual</option>");
			out.println("</select></td>");
			out.println("</tr>"); 
			out.println("<tr >"); 
			out.println("<td width='20%' >Factoring Relationship *</td>"); 
			out.println("<td width='*%' ><select name='TXT_CLIENT_RELATIONSHIP' class='txt_input'>");
			out.println("<option value=\"D\">As a Debtor</option>");
			out.println("</select></td>");
			out.println("</tr>"); 
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CODE'  class=div_input>Client Code *</DIV></td>"); 
			out.println("<td width='*%' ><input class='txt_input' type='text' name='TXT_CLIENT_CODE' maxlength='10' size='50' style='width:150' onblur=\"\"  disabled >");  //disabled added by ns on 22-08-20011
			out.println("<input class='but_input' type='button' name='BUT_HELP_MAIN' value=\"Help\" onClick=\"help_update()\" disabled></td>"); //disabled added by ns on 22-08-20011
			//out.println("</td>"); 
			out.println("</tr>");		
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FULL_NAME'  class=div_input>Full Name *</DIV></td>"); 
			out.println("<td width='*%' ><input class='txt_input' type='text' name='TXT_CLIENT_FULL_NAME' maxlength='250' size='250' style='width:250'  onblur=\"client_detail_dispaly()\"></td>"); 
			out.println("</tr>");
			out.println("</table>"); 
			
			out.println("<br>"); 
			out.println("<table   width=\"100%\">"); 
			out.println("<tr >"); 
			out.println("<td width='20%'  class=div_input><b><u>General Information</u></b></td>"); 
			out.println("<td width='*%' ></td>");
			out.println("</tr>"); 
			out.println("</table>");
			out.println("<br>"); 
			out.println("<DIV id='client_general_data'  class=div_input></DIV>");//popu;ate client general data
			out.println("<br>"); 
			out.println("<table width=\"100%\">");
			out.println("<tr>"); 
			out.println("<td width=\"20%\"><DIV id=\"DIV_TXT_CLIENT_GROUP\"  class=div_input>Client Classification </DIV></td>"); 
			out.println("<td width=\"25%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_GROUP\" maxlength=\"10\" size=\"50\" style=\"width:100\" onblur=\"help_update_client_group()\">");
			out.println("<input class=\"but_input\" type=\"button\" name=\"BUT_HELP_LIENT_GROUP\" value=\"Help\" onClick=\"help_update_client_group()\"></td>"); 
			out.println("<td width=\"5%\"></td>");  
			out.println("<td width=\"15%\"></td>");
			out.println("<td width=\"*%\"></td>");
			out.println("</tr>");	
			out.println("<tr>"); 
			out.println("<td width=\"20%\"><DIV id=\"DIV_TXT_CRIB_STATUS\"  class=div_input>CRIB Status </DIV></td>"); 
			out.println("<td width='25%' ><select name='TXT_CLIENT_CRIB' class='txt_input' onchange='enable_comment(this.value)' >");
			out.println("<OPTION value=\"REGULAR\" SELECTED >Regular </option>");
			out.println("<OPTION value=\"IRREGULAR\" >Irregular </option></SELECT>");
			out.println("</td>");
			out.println("<td width=\"5%\"></td>");  
			out.println("<td width=\"15%\" id=\"comment\"><DIV id=\"DIV_TXT_CRIB_STATUS_COMMENT\"  class=div_input>Comments </DIV> </td>");
			out.println("<td width=\"*%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_CLIENT_CRIB_COMMENT\" maxlength=\"200\" size=\"50\" style=\"width:250\"></td>"); 
			out.println("</tr>");	
			out.println("<tr>"); 
			out.println("<td width=\"20%\"><DIV id=\"DIV_TXT_3RD_PARTY_STATUS\"  class=div_input>Debtors Assigned To a Third Party </DIV></td>"); 
			out.println("<td width='25%' ><select name='TXT_3RD_PARTY_STATUS' class='txt_input' onchange='enable_specify(this.value)' >");
			out.println("<OPTION value=\"Y\"  >Yes </option>");
			out.println("<OPTION value=\"N\" SELECTED>No </option></SELECT>");
			out.println("</td>");
			out.println("<td width=\"5%\"></td>");  
			out.println("<td width=\"15%\" id=\"specify\">Specify </td>");
			out.println("<td width=\"*%\"><input class=\"txt_input\" type=\"text\" name=\"TXT_3RD_PARTY_DEBTOR_DET\" maxlength=\"200\" size=\"50\" style=\"width:250\" disabled ></td>");
			out.println("</tr>");
			out.println("</table>");
			out.println("<br>");
			out.println("<table  width=\"100%\">"); 
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV class=div_input><u><b>Contact Information</b></u></DIV></td>"); 
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_HOME_STATUS'  class=div_input>Home/Registered Office Status </DIV></td>"); 
			out.println("<td width='25%' ><select name='TXT_CLIENT_HOME_STATUS' class='txt_input'>");
			out.println("<OPTION value=\"OWN\" SELECTED >Own </option>");
			out.println("<OPTION value=\"RENT\" >Rent </option>");
			out.println("<OPTION value=\"MORTGAGED\" >Mortgaged </option>");
			out.println("<OPTION value=\"WITH_PARENTS\" >With Parents </option></SELECT>");
			out.println("</td>");
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_HOME_ADDRESS1'  class=div_input>Home/Registered Office Address *</DIV></td>"); //address feild
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_HOME_ADDRESS1' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_HOME_TELEPHONE'  class=div_input>Telephone - Home</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_HOME_TELEPHONE' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_HOME_ADDRESS2'  class=div_input></DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_HOME_ADDRESS2' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_OFFICE_TELEPHONE'  class=div_input>Telephone - Office</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_OFFICE_TELEPHONE' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");		
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CITY'  class=div_input>City </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_CITY' maxlength='10' size='50' style='width:150' onblur=\"help_update_city_code()\"><input class='but_input' type='button' name='BUT_HELP_CITY' value=\"Help\" onClick=\"help_update_city_code()\"></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FAXNO'  class=div_input>Fax No</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FAXNO' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_COLLECTION_AREA'  class=div_input>Area *</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_COLLECTION_AREA' maxlength='10' size='50' style='width:150' onblur=\"help_update_collection_location_code()\"><input class='but_input' type='button' name='BUT_HELP_COLLECTION_LOCATION' value=\"Help\" onClick=\"help_update_collection_location_code()\"></td>"); 
			out.println("<td width='5%'></td>"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_MOBILE'  class=div_input>Mobile No</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_MOBILE' maxlength='30' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_REFERENCE'  class=div_input>Reference </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_REFERENCE' maxlength='200' size='50' style='width:150'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_EMAIL'  class=div_input>Email Address</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_EMAIL' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");  
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_KEY_DECISION_MAKER'  class=div_input>Key Decision Maker </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_KEY_DECISION_MAKER' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");    
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CONT_PERSON'  class=div_input>Contact Person *</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_CONT_PERSON' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_DESIG_PAYMENT'  class=div_input>Contact Person Designation </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_DESIG_PAYMENT' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<br>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_STATUS'  class=div_input>Factory Status </DIV></td>"); 
			out.println("<td width='25%' ><select name='TXT_CLIENT_FACTORY_STATUS' class='txt_input'>");
			out.println("<OPTION value=\"OWN\" >Own </option>");
			out.println("<OPTION value=\"RENT\" >Rent </option>");
			out.println("<OPTION value=\"MORTGAGED\" >Mortgaged </option>");
			out.println("<OPTION value=\"WITH_PARENTS\" >With Parents </option>");
			out.println("<OPTION value=\"N/A\" SELECTED >N/A</option></SELECT>");
			out.println("</td>");
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_ADDRESS1'  class=div_input>Factory Address </DIV></td>"); //factory feild
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_ADDRESS1' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_TELEPHONE'  class=div_input>Telephone - Factory</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_TELEPHONE' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_ADDRESS2'  class=div_input></DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_ADDRESS2' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_FAX'  class=div_input>Fax - Factory</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_FAX' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");   
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_EMAIL'  class=div_input>Email Address - Factory</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_EMAIL' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_FACTORY_CONPERSON'  class=div_input>Contact Person - Factory</DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_FACTORY_CONPERSON' maxlength='200' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_STATUS'  class=div_input>Correspondence Office Status </DIV></td>"); 
			out.println("<td width='25%' ><select name='TXT_CLIENT_CORESSS_STATUS' class='txt_input'>");
			out.println("<OPTION value=\"OWN\" SELECTED >Own </option>");
			out.println("<OPTION value=\"RENT\" >Rent </option>");
			out.println("<OPTION value=\"MORTGAGED\" >Mortgaged </option>");
			out.println("<OPTION value=\"WITH_PARENTS\" >With Parents </option></SELECT>");
			out.println("</td>");
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ></td>");
			out.println("<td width='25%' ></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_ADDRESS1'  class=div_input>Correspondence Office Address </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CORESSS_HOMEADDRESS1' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_TELEPHONE'  class=div_input>Telephone </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_CORESSS_TELEPHONE' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_ADDRESS2'  class=div_input></DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CORESSS_HOMEADDRESS2' maxlength='100' size='100' style='width:200'></td>"); 
			out.println("<td width='5%'></td>");  
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_FAX'  class=div_input>Fax </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_CORESSS_FAX' maxlength='60' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");		
			out.println("<tr >"); 
			out.println("<td width='20%' ><DIV id='DIV_TXT_CORESSS_CITY'  class=div_input>City </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CORESSS_CITY' maxlength='10' size='50' style='width:150' onblur=\"help_update_city_code_2()\"><input class='but_input' type='button' name='BUT_HELP_CITY' value=\"Help\" onClick=\"help_update_city_code_2()\"></td>"); 
			out.println("<td width='5%'></td>");   
			out.println("<td width='20%' ><DIV id='DIV_TXT_CLIENT_CORESSS_EMAIL'  class=div_input>Email Address  </DIV></td>");
			out.println("<td width='25%' ><input class='txt_input' type='text' name='TXT_CLIENT_CORESSS_EMAIL' maxlength='50' size='100' style='width:200'></td>");
			out.println("<td width='*%'></td>");   
			out.println("</tr>");
			out.println("</table>");
			out.println("<br>"); 

			out.println("<table align='center' width='100%'>"); 
			out.println("<tr>"); 
			out.println("<td width='100%' class='note'></td>"); 
			out.println("</tr>"); 
			out.println("</table>"); 
			out.println("</form>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/validate.js'></SCRIPT>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/validate_v2.js'></SCRIPT>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/factoring_drill_down.js'></SCRIPT>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/ajax_data_gateway.js'></SCRIPT>"); 
			out.println("</body>"); 
			out.println("</html>"); 
			System.gc();
			out.flush();
		}
		catch (Exception ex) {
			try{out.println("Error:"+ex.toString());}catch(Exception e){}
		}
		finally{
				if(out!=null){
					try{out.close();  
					}catch(Exception e){}
				}
		}
	}
}



