// DEVELOP BY : INDITHA FOR OFSCL FACTORING    DATE:21-09-2006
         

import java.io.*; 
import javax.servlet.*; 
import javax.servlet.http.*; 
import java.sql.*; 
import java.util.*; 
 

public class LAKDL_FA_CR_display_client_debtor extends javax.servlet.http.HttpServlet { 

	ServletOutputStream out = null;
	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
		 
		try { 
			 
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String m_header_name=m_sn_methods.header_name.trim();
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			out = res.getOutputStream(); 
			 
			out.println("<HTML>"); 
			out.println("<HEAD>"); 
			out.println("<TITLE>Credit Process - Assign Debtors to Client Facility</TITLE>"); 
			out.println("</HEAD>"); 
			out.println("<link REL='STYLESHEET' HREF='"+m_html_client_url+"/css/Asset_Financing_System.css' TYPE=\"text/css\">"); 
			out.println("<SCRIPT language=\"JavaScript\">"); 
			     
			out.println("var m_sav_msg='';");
			
			out.println("function get_vector(data_vec) {");
			out.println("		if(data_vec.length>0 && document.Form1.hid_display_client.value==\"0\"){");
			out.println("		}");
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"1\"){");
			out.println("			m_act_len=parseInt(data_vec.length)/4;");
			out.println("			m_act_len=parseInt(m_act_len)-parseInt(document.Form1.hid_product_count.value);");
			out.println("			for(var i=1;i<=parseInt(m_act_len);i++){");
			out.println("				add_products();");
			out.println("			}");
			out.println("			var m_count=0;");
			out.println("   	for(k=1;k<=parseInt(document.Form1.hid_product_count.value);k++){");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_CODE_\"+k].value=data_vec[m_count];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_DESC_\"+k].value=data_vec[m_count+1];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_COMMENT_\"+k].value=data_vec[m_count+2];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_PARAM_\"+k].value=data_vec[m_count+3];");
			out.println("   		m_count=m_count+4;");
			out.println("			}");
			out.println("  		makeRequest(2);");
			out.println("		}");
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"2\"){");
			out.println("			m_act_len=parseInt(data_vec.length)/4;");
			out.println("			m_act_len=parseInt(m_act_len)-parseInt(document.Form1.hid_fee_count.value);");
			out.println("			for(var i=1;i<=parseInt(m_act_len);i++){");
			out.println("				add_fee();");
			out.println("			}");
			out.println("			var m_count=0;");
			out.println("   	for(k=1;k<=parseInt(document.Form1.hid_fee_count.value);k++){");
			out.println("   		document.Form1.elements[\"TXT_FEE_CODE_\"+k].value=data_vec[m_count];");
			out.println("   		document.Form1.elements[\"TXT_FEE_DESC_\"+k].value=data_vec[m_count+1];");
			out.println("   		document.Form1.elements[\"TXT_FEE_TYPE_\"+k].value=data_vec[m_count+2];");
			out.println("   		document.Form1.elements[\"TXT_FEE_VALUE_\"+k].value=data_vec[m_count+3];");
			out.println("   		m_count=m_count+4;");
			out.println("			}");
			out.println("  		makeRequest(99);");
			out.println("		}");
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"3\"){");
			out.println("			document.Form1.TXT_FACILITY_NO.value=data_vec[0];");
			out.println("			document.Form1.TXT_CLIENT_CODE.value=data_vec[1];");
			out.println("			document.Form1.TXT_CLIENT_NAME.value=data_vec[2];");
			out.println("			document.Form1.TXT_FACILITY_MANAGER_NAME.value=data_vec[5];");
			out.println("			document.Form1.TXT_TOT_CREDIT_LIMIT.value=data_vec[8];");
			out.println("			document.Form1.TXT_DEBTOR_CODE.value=data_vec[3];");
			out.println("			document.Form1.TXT_DEBTOR_NAME.value=data_vec[4];");
			out.println("			document.Form1.TXT_CLIENT_MMGR.value=data_vec[6];");
			out.println("			document.Form1.TXT_CLIENT_MMGR_NAME.value=data_vec[7];"); 
			out.println("			document.Form1.TXT_PRODUCT_CODE.value=data_vec[9];");
			out.println("			document.Form1.TXT_PRODUCT_DESC.value=data_vec[10];");
			out.println("			document.Form1.TXT_FEE_CODE.value=data_vec[11];");
			out.println("			document.Form1.TXT_FEE_DESC.value=data_vec[12];");
			out.println("			document.Form1.TXT_CREDIT_LIMIT.value=data_vec[13];");
			out.println("			document.Form1.TXT_CREDIT_PERIOD.value=data_vec[14];");
			out.println("			document.Form1.TXT_TOL_CREDIT_PERIOD.value=data_vec[15];");
			out.println("	  	document.Form1.TXT_RES_MARGIN.value=data_vec[16];");
			out.println("			document.Form1.TXT_CLIENT_DESIG_PAYMENT.value=data_vec[17];");
			out.println("	  	document.Form1.TXT_CLIENT_CONT_PERSON.value=data_vec[18];");
			out.println("			format_num(document.Form1.TXT_TOT_CREDIT_LIMIT,4);");
			out.println("  		makeRequest(1);");
			out.println("		}");
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"4\"){");
			out.println("			m_act_len=parseInt(data_vec.length)/4;");
			out.println("			m_act_len=parseInt(m_act_len)-parseInt(document.Form1.hid_product_count.value);");
			out.println("			for(var i=1;i<=parseInt(m_act_len);i++){");
			out.println("				add_products();");
			out.println("			}");
			out.println("			var m_count=0;");
			out.println("   	for(k=1;k<=parseInt(document.Form1.hid_product_count.value);k++){");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_CODE_\"+k].value=data_vec[m_count];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_DESC_\"+k].value=data_vec[m_count+1];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_COMMENT_\"+k].value=data_vec[m_count+2];");
			out.println("   		document.Form1.elements[\"TXT_PRODUCT_FEATURE_PARAM_\"+k].value=data_vec[m_count+3];");
			out.println("   		m_count=m_count+4;");
			out.println("			}");
			out.println("		document.Form1.BUT_HELP_PRODUCT_MAIN_ADD.disabled=true;");
			//out.println("  	makeRequest(5);");
			out.println("  	makeRequest(2);");
			out.println("		}");
			out.println("		else if(data_vec.length>0 && document.Form1.hid_display_client.value==\"5\"){");
			out.println("			m_act_len=parseInt(data_vec.length)/4;");		
			out.println("			m_act_len=parseInt(m_act_len)-parseInt(document.Form1.hid_fee_count.value);");
			out.println("			for(var i=1;i<=parseInt(m_act_len);i++){");
			out.println("				add_fee();");
			out.println("			}");
			out.println("			var m_count=0;");
			out.println("   	for(k=1;k<=parseInt(document.Form1.hid_fee_count.value);k++){");
			out.println("   		document.Form1.elements[\"TXT_FEE_CODE_\"+k].value=data_vec[m_count];");
			out.println("   		document.Form1.elements[\"TXT_FEE_DESC_\"+k].value=data_vec[m_count+1];");
			out.println("   		document.Form1.elements[\"TXT_FEE_TYPE_\"+k].value=data_vec[m_count+2];");
			out.println("   		document.Form1.elements[\"TXT_FEE_VALUE_\"+k].value=data_vec[m_count+3];");
			out.println("   		m_count=m_count+4;");
			out.println("			}");
			out.println("		document.Form1.BUT_HELP_FEE_MAIN_ADD.disabled=true;");
			out.println("  	makeRequest(99);");
			out.println("		}");	
			out.println("}");
			
			out.println("function makeRequest(m_val) {");
			out.println("		if(m_val==\"1\"){");
			out.println("			document.Form1.hid_display_client.value=1;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_NEW_PRODUCT_FEATURE&facility_code=\"+document.Form1.TXT_FACILITY_NO.value+\"&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			//out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_NEW_PRODUCT_FEATURE&product_code=\"+document.Form1.TXT_PRODUCT_CODE.value;");
			out.println("		}");
			out.println("		else if(m_val==\"2\"){");
			out.println("			document.Form1.hid_display_client.value=2;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_NEW_FEE_FEATURE&facility_code=\"+document.Form1.TXT_FACILITY_NO.value+\"&client_code=\"+document.Form1.TXT_CLIENT_CODE.value;");
			//out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_NEW_FEE_FEATURE&fee_code=\"+document.Form1.TXT_FEE_CODE.value;");
			out.println("		}");
			out.println("		else if(m_val==\"3\"){");
			out.println("			document.Form1.hid_display_client.value=3;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_EDIT_DEBTOR_MAIN&facility_code=\"+document.Form1.TXT_FACILITY_NO.value+\"&debtor_code=\"+document.Form1.TXT_DEBTOR_CODE.value;");
			out.println("			//window.open(m_url);");
			out.println("		}");
			out.println("		else if(m_val==\"4\"){");
			out.println("			document.Form1.hid_display_client.value=4;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_EDIT_DEBTOR_PRODUCT&facility_code=\"+document.Form1.TXT_FACILITY_NO.value+\"&debtor_code=\"+document.Form1.TXT_DEBTOR_CODE.value;");
			out.println("		}");
			out.println("		else if(m_val==\"5\"){");
			out.println("			document.Form1.hid_display_client.value=5;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=m_EDIT_DEBTOR_FEE&facility_code=\"+document.Form1.TXT_FACILITY_NO.value+\"&debtor_code=\"+document.Form1.TXT_DEBTOR_CODE.value;");
			out.println("		}");
			out.println("		else if(m_val==\"99\"){");
			out.println("			document.Form1.hid_display_client.value=99;");
			out.println("			m_url=\""+m_class_url+"/"+m_fschema_name+"FA_CR_sql_validations?chksql=idle\";");
			out.println("		}");
			out.println("		load_interface(m_url,'XML');");
			out.println("}");
			
			out.println("function add_products(){"); 
			out.println("		 m_dir_count=parseInt(document.Form1.hid_product_count.value);");
			out.println("		 m_dir_count++;");
			out.println("		 if(parseInt(document.Form1.hid_product_count.value)==0){");
			out.println("		 product_detail_data.innerHTML=\"\";"); 
			out.println("		 }");
			out.println("		 product_detail_data.innerHTML=product_detail_data.innerHTML+'<table  width=\"100%\">'+"); 
			out.println("		 '<tr>'+"); 
			out.println("		 '<td width=\"15%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_CODE_'+m_dir_count+'\" maxlength=\"100\"  disabled><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_PRODUCT_MAIN\" value=\"Help\" onClick=\"help_products_feature('+m_dir_count+')\" disabled></td>'+"); 
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_DESC_'+m_dir_count+'\" maxlength=\"100\" style=\"width:200\" disabled></td>'+");
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_COMMENT_'+m_dir_count+'\" maxlength=\"100\" style=\"width:200\"  disabled></td>'+");
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_PARAM_'+m_dir_count+'\" maxlength=\"25\" disabled><input class=\"but_input\" type=\"button\" name=\"BUT_DELETE_DIRECTOR_MAIN\" value=\"Delete\" onClick=\"delete_products('+m_dir_count+')\" disabled></td>'+");
			out.println("		 '<td width=\"*%\" class=div_input></td>'+");
			out.println("		 '</tr>'+"); 
			out.println("		 '</table>';"); 
			out.println("		 document.Form1.hid_product_count.value=m_dir_count;");
			out.println("}"); 
			
			out.println("function delete_products(mnum){");
			out.println("	if(parseInt(mnum)>0){");
			out.println("		 m_dir_count=parseInt(document.Form1.hid_product_count.value);");
			out.println("    m_count=0;");
			out.println("    m_str=\"\";");
			out.println("    for(k=1;k<=m_dir_count;k++){");
			out.println("    	if(k!=mnum){");
			out.println("		 		m_count++;");
			out.println("    		obj1=document.Form1.elements[\"TXT_PRODUCT_FEATURE_CODE_\"+k].value;");
			out.println("    		obj2=document.Form1.elements[\"TXT_PRODUCT_FEATURE_DESC_\"+k].value;");
			out.println("    		obj3=document.Form1.elements[\"TXT_PRODUCT_FEATURE_COMMENT_\"+k].value;");
			out.println("    		obj4=document.Form1.elements[\"TXT_PRODUCT_FEATURE_PARAM_\"+k].value;");
			out.println("		 		m_str=m_str+'<table  width=\"100%\">'+"); 
			out.println("		 		'<tr>'+"); 
			out.println("		 		'<td width=\"15%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_CODE_'+m_count+'\" maxlength=\"100\"  disabled value=\"'+obj1+'\"><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_PRODUCT_MAIN\" value=\"Help\" onClick=\"help_products_feature('+m_count+')\"></td>'+"); 
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_DESC_'+m_count+'\" maxlength=\"100\" disabled style=\"width:200\" value=\"'+obj2+'\"></td>'+");
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_COMMENT_'+m_count+'\" maxlength=\"100\" disabled style=\"width:200\" value=\"'+obj3+'\"></td>'+");
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_PRODUCT_FEATURE_PARAM_'+m_count+'\" maxlength=\"25\" value=\"'+obj4+'\"><input class=\"but_input\" type=\"button\" name=\"BUT_DELETE_PRODUCT_MAIN\" value=\"Delete\" onClick=\"delete_products('+m_count+')\"></td>'+");
			out.println("		 		'<td width=\"*%\" class=div_input></td>'+");
			out.println("		 		'</tr>'+"); 
			out.println("		 		'</table>';");
			out.println("    	}");
			out.println("	 	 }");
			out.println("		 product_detail_data.innerHTML=m_str;");
			out.println("		 document.Form1.hid_product_count.value=m_count;");
			out.println("	}");
			out.println("}"); 
			
			out.println("function add_fee(){"); 
			out.println("		 m_dir_count=parseInt(document.Form1.hid_fee_count.value);");
			out.println("		 m_dir_count++;");
			out.println("		 if(parseInt(document.Form1.hid_fee_count.value)==0){");
			out.println("		 fee_detail_data.innerHTML=\"\";"); 
			out.println("		 }");
			out.println("		 fee_detail_data.innerHTML=fee_detail_data.innerHTML+'<table  width=\"100%\">'+"); 
			out.println("		 '<tr>'+"); 
			out.println("		 '<td width=\"15%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_CODE_'+m_dir_count+'\" maxlength=\"100\"  disabled><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_FEE_MAIN\" value=\"Help\" onClick=\"help_fee_feature('+m_dir_count+')\" disabled></td>'+"); 
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_DESC_'+m_dir_count+'\" maxlength=\"100\" style=\"width:200\" disabled></td>'+");
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_TYPE_'+m_dir_count+'\" maxlength=\"100\" style=\"width:200\"  disabled></td>'+");
			out.println("		 '<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_VALUE_'+m_dir_count+'\" maxlength=\"25\"  onblur=\"format_number2(this,20)\"  style=\"text-align:right\" disabled><input class=\"but_input\" type=\"button\" name=\"BUT_DELETE_FEE_MAIN\" value=\"Delete\" onClick=\"delete_fee('+m_dir_count+')\" disabled></td>'+");
			out.println("		 '<td width=\"*%\" class=div_input></td>'+");
			out.println("		 '</tr>'+"); 
			out.println("		 '</table>';"); 
			out.println("		 document.Form1.hid_fee_count.value=m_dir_count;");
			out.println("}"); 

			out.println("function delete_fee(mnum){");
			out.println("	if(parseInt(mnum)>0){");
			out.println("		 m_dir_count=parseInt(document.Form1.hid_fee_count.value);");
			out.println("    m_count=0;");
			out.println("    m_str=\"\";");
			out.println("    for(k=1;k<=m_dir_count;k++){");
			out.println("    	if(k!=mnum){");
			out.println("		 		m_count++;");
			out.println("    		obj1=document.Form1.elements[\"TXT_FEE_CODE_\"+k].value;");
			out.println("    		obj2=document.Form1.elements[\"TXT_FEE_DESC_\"+k].value;");
			out.println("    		obj3=document.Form1.elements[\"TXT_FEE_TYPE_\"+k].value;");
			out.println("    		obj4=document.Form1.elements[\"TXT_FEE_VALUE_\"+k].value;");
			out.println("		 		m_str=m_str+'<table  width=\"100%\">'+"); 
			out.println("		 		'<tr>'+"); 
			out.println("		 		'<td width=\"15%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_CODE_'+m_count+'\" maxlength=\"100\"  disabled value=\"'+obj1+'\"><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_FEE_MAIN\" value=\"Help\" onClick=\"help_fee_feature('+m_count+')\"></td>'+"); 
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_DESC_'+m_count+'\" maxlength=\"100\" disabled style=\"width:200\" value=\"'+obj2+'\"></td>'+");
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_TYPE_'+m_count+'\" maxlength=\"100\" disabled style=\"width:200\" value=\"'+obj3+'\"></td>'+");
			out.println("		 		'<td width=\"20%\" class=div_input><input class=\"txt_input\" type=\"text\" name=\"TXT_FEE_VALUE_'+m_count+'\" maxlength=\"25\" value=\"'+obj4+'\"  onblur=\"format_number2(this,20)\"  style=\"text-align:right\"><input class=\"but_input\" type=\"button\" name=\"BUT_DELETE_FEE_MAIN\" value=\"Delete\" onClick=\"delete_fee('+m_count+')\"></td>'+");
			out.println("		 		'<td width=\"*%\" class=div_input></td>'+");
			out.println("		 		'</tr>'+"); 
			out.println("		 		'</table>';");
			out.println("    	}");
			out.println("	 	 }");
			out.println("		 fee_detail_data.innerHTML=m_str;");
			out.println("		 document.Form1.hid_fee_count.value=m_count;");
			out.println("	}");
			out.println("}"); 
			
			out.println("function makeRequest_detail_Fee() {");
			out.println("	  document.Form1.hid_option.value=\"3\";");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MK_PRO_sql_validations_normal?chksql=FEE_PACKAGES&fee_pack_id=\"+document.Form1.TXT_FEE_CODE.value;");
			out.println("		load_interface(m_url,'NO');");
			out.println("}");
			
			out.println("function makeRequest_detail_Product() {");
			out.println("	  document.Form1.hid_option.value=\"2\";");
			out.println("		m_url=\""+m_class_url+"/"+m_fschema_name+"FA_MK_PRO_sql_validations_normal?chksql=PRODUCT_PACKAGES&product_id=\"+document.Form1.TXT_PRODUCT_CODE.value;");
			out.println("		load_interface(m_url,'NO');");
			out.println("}");
			
			out.println("function validate_data(){"); 
			out.println("	if(document.Form1.TXT_FACILITY_NO.value==\"\" ){  "); 
			out.println("		DIV_TXT_FACILITY_NO.style.color='red';");
			out.println("		return false;"); 
			out.println("	}"); 
			out.println("	else if(document.Form1.TXT_CLIENT_CODE.value==\"\"){  "); 
			out.println("		DIV_TXT_CLIENT_CODE.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_DEBTOR_CODE.value==\"\"){  "); 
			out.println("		DIV_TXT_DEBTOR_CODE.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CLIENT_MMGR.value==\"\"){  "); 
			out.println("		DIV_TXT_CLIENT_MMGR.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CREDIT_LIMIT.value==\"\"){  "); 
			out.println("		DIV_TXT_CREDIT_LIMIT.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_CREDIT_PERIOD.value==\"\"){  "); 
			out.println("		DIV_TXT_CREDIT_PERIOD.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_TOL_CREDIT_PERIOD.value==\"\"){  "); 
			out.println("		DIV_TXT_TOL_CREDIT_PERIOD.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_RES_MARGIN.value==\"\"){  "); 
			out.println("		DIV_TXT_RES_MARGIN.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_PRODUCT_CODE.value==\"\"){  "); 
			out.println("		DIV_TXT_PRODUCT_CODE.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else if(document.Form1.TXT_FEE_CODE.value==\"\"){  "); 
			out.println("		DIV_TXT_FEE_CODE.style.color='red';");
			out.println("		return false;"); 
			out.println("	}");
			out.println("	else{"); 
			out.println("		return true;"); 
			out.println("	}"); 
			out.println("}"); 			

			out.println("function before_submit(){ "); 
			out.println("	get_display_msg();");
			out.println("	if(validate_data()){"); 
			out.println("		if(confirm(\"Are you sure you want to \"+m_sav_msg+\" ?\")){ ");
			out.println("			for (var i=0; i < document.Form1.elements.length; i++ ) {");
			out.println("				document.Form1.elements[i].disabled=false;");
			out.println("			}");
			out.println("			if(validate_data()){"); 
			out.println("				document.Form1.action='"+m_class_url+"/"+m_fschema_name+"FA_CR_Save_client_debtor_creation';");  
			out.println("				document.Form1.submit();	"); 
			out.println("			}"); 
			out.println("		}"); 
			out.println("	}"); 
			out.println("		else { "); 
			out.println("		alert(\"Please enter all required fields marked with a '*' on screen.\"); ");
			out.println("		}");
			out.println("} "); 

			out.println("function load_lock(){	"); 
			//out.println("document.oncontextmenu=new Function(\"return false\");"); 
			out.println("}	"); 

			out.println("function clear_window(){	"); 
			out.println("		if(confirm(\"Are you sure you want to clear the screen ?\")){ "); 
			out.println("		window.location.href='"+m_class_url+"/"+m_fschema_name+"FA_CR_display_client_debtor';"); 
			out.println("		}"); 
			out.println("}"); 
			
			out.println("function new_window(){	"); 
			out.println("		window.location.href='"+m_class_url+"/"+m_fschema_name+"FA_CR_display_client_debtor';"); 
			out.println("}"); 

			out.println("function save_window(){	"); 
			out.println("	before_submit();"); 
			out.println("}"); 

			out.println("function load_help_msg() {"); 
			out.println("    m_help_message = \"m_help_msg_LAKDL_FA_CR_CLIENT_DEBTOR_CREATION\";"); 
			out.println("    HelpBox_msg(m_help_message);"); 
			out.println("}"); 	
			
			out.println("function HelpBox_msg(m_help_message) {"); 
			out.println("		popupwin = window.showModalDialog(servlet_client_url+\":\"+client_t3_port+\"/\"+client_name+\"AF_MAS_Help_Msg_Servlet?class_in=\"+client_name+\"FA_MAS_Help_Msg_select\"+"); 
			out.println("  \"&help_message_in=\"+m_help_message);"); 
			out.println("}"); 
 
			out.println("function load_roll_value(m_val){"); 
			out.println("	help_box.innerHTML=\"  Credit Process - Assign Debtors to Client Facility- \"+m_val;"); 
			out.println("}"); 

			out.println("function load_roll_out_value(){");
			out.println("	help_box.innerHTML=\"  Credit Process - Assign Debtors to Client Facility- \"+document.Form1.hid_status.value;"); 
			out.println("}"); 

			out.println("function load_screen_status(m_val){"); 
			//out.println("	if(confirm(\"Are You Sure\")){ ");
			out.println("		if(m_val==\"NEW\"){"); 
			out.println("			new_window();"); 
			out.println("		}"); 
			out.println("		else if(m_val==\"HELP\"){"); 
			out.println("			load_help_msg();"); 
			out.println("		}"); 
			out.println("		document.Form1.SCREEN_NAME.value=m_val;"); 
			out.println("		if(m_val==\"NEW\"){");
			out.println("			document.Form1.hid_status.value=\"New\";"); 
			out.println("		}");
			out.println("		else if(m_val==\"EDIT\"){");  
			out.println("			document.Form1.hid_status.value=\"Edit\";");  
			out.println("		}");
			out.println("		else if(m_val==\"DACT\"){");  
			out.println("			document.Form1.hid_status.value=\"Deactivate\";");  
			out.println("		}");
			out.println("		else if(m_val==\"RACT\"){");  
			out.println("			document.Form1.hid_status.value=\"Reactivate\";");  
			out.println("		}");
			out.println("		else{");  
			out.println("			document.Form1.hid_status.value=\"\";");  
			out.println("		}"); 
			//out.println("	}"); 
			out.println("}"); 
			   
			out.println("function get_display_msg(){"); 
			out.println("	if(document.Form1.SCREEN_NAME.value==\"NEW\"){");
			out.println("		m_sav_msg=\"Save\";"); 
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"EDIT\"){");  
			out.println("		m_sav_msg=\"Modify\";");  
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"DACT\"){");  
			out.println("		m_sav_msg=\"Deactivate\";");  
			out.println("	}");
			out.println("	else if(document.Form1.SCREEN_NAME.value==\"RACT\"){");  
			out.println("		m_sav_msg=\"Reactivate\";");  
			out.println("	}");
			out.println("	else{");  
			out.println("		m_sav_msg=\"\";");  
			out.println("	}"); 
			out.println("}"); 

			out.println("function MyDialog(){"); 
			out.println("	this.valout   = new Array(10);"); 
			out.println("}"); 

			out.println("function HelpBox(Start,End,Hid_No,Max) {"); 
			out.println("    oBj = new MyDialog();"); 
			out.println("    oBj.valout[1]  = \" \";"); 
			out.println("    oBj.valout[2]  = \" \";"); 
			out.println("    oBj.valout[3]  = \" \";"); 
			out.println("	"); 
			out.println("	popupwin = window.showModalDialog(servlet_client_url+\":\"+client_t3_port+\"/\"+client_name+\"FA_MAS_Help_Servlet?class_in=\"+client_name+\"FA_CR_help_select\"+"); 
			out.println("    \"&Sql_in=\"+m_sql+\"&Start_in=\"+Start+"); 
			out.println("    \"&End_in=\"+End+\"&Crit_In=\"+m_criteria+"); 
			out.println("    \"&Hid_No=\"+Hid_No, oBj,\"dialogWidth:45em; dialogHeight:18em; center:yes; status:no\");"); 
			out.println("	if(oBj.valout[1] !=\" \"){"); 
			out.println("		if(oBj.valout[1] !=\"Close\"){"); 
			out.println("			if(oBj.valout[1]!=\"Prev\"){"); 
			out.println("				if(oBj.valout[1]!=\"Next\"){"); 
			out.println("					if(document.Form1.hid_help_type.value==\"1\"){"); 
			out.println("						help_update_value_1();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"2\"){"); 
			out.println("						help_update_value_2();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"3\"){"); 
			out.println("						help_update_value_3();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"4\"){"); 
			out.println("						help_update_value_4();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"5\"){"); 
			out.println("						help_update_value_5();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"6\"){"); 
			out.println("						help_update_value_6();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"7\"){"); 
			out.println("						help_update_value_7();"); 
	  	out.println("					}"); 
			out.println("					else if(document.Form1.hid_help_type.value==\"8\"){"); 
			out.println("						help_update_value_8();"); 
	  	out.println("					}"); 
			out.println("				}"); 
			out.println("				else{"); 
			out.println("					Next(oBj.valout[2],oBj.valout[3],Hid_No);"); 
			out.println("					return false;"); 
			out.println("				} "); 
			out.println("			}"); 
			out.println("			else{	"); 
			out.println("				Prev(oBj.valout[2],oBj.valout[3],Hid_No);"); 
			out.println("			}	"); 
			out.println("	 	}"); 
			out.println("	 	else{"); 
			out.println("	 		clear_data();");
			out.println("		}"); 
			out.println("	}"); 
			out.println("	else{"); 
			out.println("		clear_data();");
			out.println("	}"); 
			out.println("}"); 

			out.println("function Prev(Start,End,Hid_No){"); 
			out.println("		HelpBox(Start,End,Hid_No);"); 
			out.println("}"); 

			out.println("function Next (Start,End,Hid_No){"); 
			out.println("		HelpBox(Start,End,Hid_No);"); 
			out.println("}"); 
			
			out.println("function clear_data(){"); 
			out.println("		if(document.Form1.hid_help_type.value==\"1\"){"); 
			out.println("		document.Form1.TXT_FACILITY_NO.value=\"\";");
			out.println("		document.Form1.TXT_CLIENT_CODE.value=\"\";");
			out.println("		document.Form1.TXT_CLIENT_NAME.value=\"\";");
			out.println("		document.Form1.TXT_CREDIT_LIMIT.value=\"\";");
			out.println("		document.Form1.TXT_FACILITY_MANAGER_NAME.value=\"\";");
			out.println("		document.Form1.TXT_TOT_CREDIT_LIMIT.value=\"\";");
	  	out.println("		}"); 
			out.println("		else if(document.Form1.hid_help_type.value==\"2\"){"); 
			out.println("		document.Form1.TXT_DEBTOR_CODE.value=\"\";");
			out.println("		document.Form1.TXT_DEBTOR_NAME.value=\"\";");
			out.println("		document.Form1.TXT_CLIENT_MMGR.value=\"\";");
			out.println("		document.Form1.TXT_CLIENT_MMGR_NAME.value=\"\";");
	  	out.println("		}"); 
			out.println("		else if(document.Form1.hid_help_type.value==\"3\"){"); 
			out.println("		document.Form1.TXT_CLIENT_MMGR.value=\"\";");
			out.println("		document.Form1.TXT_CLIENT_MMGR_NAME.value=\"\";");
	  	out.println("		}"); 
			out.println("		else if(document.Form1.hid_help_type.value==\"4\"){"); 
			out.println("		document.Form1.TXT_PRODUCT_CODE.value=\"\";");
			out.println("		document.Form1.TXT_PRODUCT_DESC.value=\"\";");
			out.println("		product_detail_data.innerHTML=\"\";");
	  	out.println("		}"); 
			out.println("		else if(document.Form1.hid_help_type.value==\"5\"){"); 
			out.println("		document.Form1.TXT_FEE_CODE.value=\"\";");
			out.println("		document.Form1.TXT_FEE_DESC.value=\"\";");
			out.println("		fee_detail_data.innerHTML=\"\";");
	  	out.println("		}"); 
			out.println("}");
			
			out.println("function help_update_facility() {"); 
			out.println("	if(document.Form1.SCREEN_NAME.value==\"NEW\"){");
			out.println(" 	document.Form1.hid_help_type.value=\"1\";"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_FACILITY_CLIENT_DETAIL_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_FACILITY_NO.value+\"@\";");
			out.println("	}");
			out.println("	else{");
			out.println(" 	document.Form1.hid_help_type.value=\"8\";"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_FACILITY_CLIENT_DETAIL_EDIT_sql\";"); 
			out.println("	 	m_criteria = document.Form1.TXT_FACILITY_NO.value+\"@\";");
			out.println("	}");
			out.println(" HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_value_8() {"); 
			out.println("		document.Form1.TXT_FACILITY_NO.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_CLIENT_CODE.value=oBj.valout[3];"); 
			out.println("		document.Form1.TXT_CLIENT_NAME.value=oBj.valout[4];"); 
			out.println("		document.Form1.TXT_DEBTOR_CODE.value=oBj.valout[5];"); 
			out.println("		document.Form1.TXT_DEBTOR_NAME.value=oBj.valout[6];"); 
			out.println("		makeRequest(3);");
			out.println("}");
			
			out.println("function help_update_value_1() {"); 
			out.println("		document.Form1.TXT_FACILITY_NO.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_CLIENT_CODE.value=oBj.valout[3];"); 
			out.println("		document.Form1.TXT_CLIENT_NAME.value=oBj.valout[4];"); 
			out.println("		document.Form1.TXT_FACILITY_MANAGER_NAME.value=oBj.valout[5];"); 
			out.println("		document.Form1.TXT_TOT_CREDIT_LIMIT.value=oBj.valout[6];"); 
			out.println("		format_num(document.Form1.TXT_TOT_CREDIT_LIMIT,4);");
			out.println("		document.Form1.TXT_FEE_CODE.value=oBj.valout[9];"); 
			out.println("		document.Form1.TXT_FEE_DESC.value=oBj.valout[10];"); 
			out.println("		document.Form1.TXT_PRODUCT_CODE.value=oBj.valout[7];"); 
			out.println("		document.Form1.TXT_PRODUCT_DESC.value=oBj.valout[8];"); 
			out.println("		document.Form1.TXT_PRODUCT_CODE.disabled=true;");
			out.println("		document.Form1.TXT_FEE_CODE.disabled=true;");
			out.println("		document.Form1.BUT_HELP_PRODUCT_MAIN_ADD.disabled=true;");
			out.println("		document.Form1.BUT_HELP_FEE_MAIN_ADD.disabled=true;");
			out.println("		document.Form1.TXT_CREDIT_LIMIT.value=oBj.valout[6];");
			out.println("		format_num(document.Form1.TXT_CREDIT_LIMIT,4);");
			out.println("		document.Form1.TXT_CREDIT_PERIOD.value=oBj.valout[11];");
			out.println("		format_num(document.Form1.TXT_CREDIT_PERIOD,4);");
			out.println("		document.Form1.TXT_TOL_CREDIT_PERIOD.value=oBj.valout[12];");
			out.println("		format_num(document.Form1.TXT_TOL_CREDIT_PERIOD,4);");
			out.println("	  document.Form1.TXT_RES_MARGIN.value=oBj.valout[13];");
			out.println("		format_num(document.Form1.TXT_RES_MARGIN,4);");
			out.println("		makeRequest(1);");
			out.println("}");
			
			out.println("function help_update_client() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"2\";"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_ASSIGN_DEBTOR_FACILITY_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_DEBTOR_CODE.value+\"@\"+document.Form1.TXT_FACILITY_NO.value+\"@\"+document.Form1.TXT_CLIENT_CODE.value+\"@\";");
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 

			out.println("function help_update_value_2() {"); 
			out.println("		document.Form1.TXT_DEBTOR_CODE.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_DEBTOR_NAME.value=oBj.valout[3];"); 
			out.println("		document.Form1.TXT_CLIENT_MMGR.value=oBj.valout[4];"); 
			out.println("		document.Form1.TXT_CLIENT_MMGR_NAME.value=oBj.valout[5];");
			out.println("		document.Form1.TXT_CLIENT_DESIG_PAYMENT.value=\"CHIEF FINANCIAL OFFICER/ACCOUNTANT\";");//ADD BY MALIK ON 5-9-2008
			//out.println("		document.Form1.TXT_CLIENT_DESIG_PAYMENT.value=oBj.valout[7];"); 
			out.println("		document.Form1.TXT_CLIENT_CONT_PERSON.value=oBj.valout[6];"); 
			out.println("}"); 
			
			out.println("function help_client_manager() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"3\";"); 
			out.println(" 	m_sql=\"m_help_DIV_TXT_CR_CLIENT_MGT_sql\";"); 
			out.println(" 	m_criteria=document.Form1.TXT_CLIENT_MMGR.value+\"@\";");
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}");
			
			out.println("function help_update_value_3() {"); 
			out.println("		document.Form1.TXT_CLIENT_MMGR.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_CLIENT_MMGR_NAME.value=oBj.valout[3];"); 
			out.println("}"); 
			
			out.println("function help_update_product() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"4\";"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_PRODUCT_FACILITY_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_PRODUCT_CODE.value+\"@\";");
			out.println(" 	HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_value_4() {"); 
			out.println("		product_detail_data.innerHTML=\"\";");
			out.println("		document.Form1.hid_product_count.value=0;");
			out.println("		document.Form1.TXT_PRODUCT_CODE.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_PRODUCT_DESC.value=oBj.valout[3];"); 
			out.println("		document.Form1.BUT_HELP_PRODUCT_MAIN_ADD.disabled=false;");
			out.println("		makeRequest(1);");
			out.println("}"); 
						
			out.println("function help_update_fee() {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"5\";"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_FEE_FACILITY_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_FEE_CODE.value+\"@\";");
			out.println("	  HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_value_5() {"); 
			out.println("		fee_detail_data.innerHTML=\"\";");
			out.println("		document.Form1.hid_fee_count.value=0;");
			out.println("		document.Form1.TXT_FEE_CODE.value=oBj.valout[2];"); 
			out.println("		document.Form1.TXT_FEE_DESC.value=oBj.valout[3];"); 
			out.println("		document.Form1.BUT_HELP_FEE_MAIN_ADD.disabled=false;");
			out.println("		makeRequest(2);");
			out.println("}"); 
			
			out.println("function help_products_feature(m_num) {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"6\";"); 
			out.println(" 	document.Form1.hid_help_count.value=m_num;"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_PRODUCT_FEATURE_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_PRODUCT_CODE.value+\"@\";");
			out.println("	  HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_value_6() {"); 
			out.println(" 	m_num=document.Form1.hid_help_count.value;"); 
			out.println("  	document.Form1.elements[\"TXT_PRODUCT_FEATURE_CODE_\"+m_num].value=oBj.valout[2];");
			out.println("  	document.Form1.elements[\"TXT_PRODUCT_FEATURE_DESC_\"+m_num].value=oBj.valout[3];");
			out.println("  	document.Form1.elements[\"TXT_PRODUCT_FEATURE_COMMENT_\"+m_num].value=oBj.valout[4];");
			out.println("  	document.Form1.elements[\"TXT_PRODUCT_FEATURE_PARAM_\"+m_num].value=oBj.valout[5];");
			out.println("}"); 
			
			out.println("function help_fee_feature(m_num) {"); 
			out.println(" 	document.Form1.hid_help_type.value=\"7\";"); 
			out.println(" 	document.Form1.hid_help_count.value=m_num;"); 
			out.println(" 	m_sql = \"m_help_DIV_TXT_FEE_FEATURE_sql\";"); 
			out.println(" 	m_criteria = document.Form1.TXT_FEE_CODE.value+\"@\";");
			out.println("	  HelpBox('1','10','0');"); 
			out.println("}"); 
			
			out.println("function help_update_value_7() {"); 
			out.println(" 	m_num=document.Form1.hid_help_count.value;"); 
			out.println("  	document.Form1.elements[\"TXT_FEE_CODE_\"+m_num].value=oBj.valout[2];");
			out.println("  	document.Form1.elements[\"TXT_FEE_DESC_\"+m_num].value=oBj.valout[3];");
			out.println("  	document.Form1.elements[\"TXT_FEE_TYPE_\"+m_num].value=oBj.valout[4];");
			out.println("  	document.Form1.elements[\"TXT_FEE_VALUE_\"+m_num].value=oBj.valout[5];");
			out.println("}"); 

			out.println("</script>"); 
			
			out.println("<BODY class='body & txt-body' leftmargin='0' topmargin='0' marginwidth='0' ONLOAD=\"load_lock();\">"); 
			out.println("<FORM NAME='Form1' method='post'>"); 
			out.println("<input  type='hidden' value='NEW' name='SCREEN_NAME'> "); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_help_type' VALUE=\"\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_help_status' VALUE=\"\">");
			out.println("<INPUT TYPE='Hidden' NAME='hid_status' VALUE=\"New\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_option' VALUE=\"99\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_product_count' VALUE=\"0\">"); 
			out.println("<INPUT TYPE='Hidden' NAME='hid_fee_count' VALUE=\"0\">");
			out.println("<INPUT TYPE='Hidden' NAME='hid_guarantee_count' VALUE=\"0\">");
			out.println("<INPUT TYPE='Hidden' NAME='hid_display_client' VALUE=\"99\">");
			out.println("<INPUT TYPE='Hidden' NAME='hid_help_count' VALUE=\"0\">");
			
			out.println("<table width='100%' class=table border='0' cellspacing='0' cellpadding='0'>"); 
			out.println("<tr>"); 
			out.println("<td width='8' valign='top'><img src='spacer.gif' width='8' height='8'></td>"); 
			out.println("<td class='border_wht' valign='top'> "); 
			out.println("<table class='table' width='100%' border='0' cellspacing='0' cellpadding='0' height='100%'>"); 
			out.println("<tr> "); 
			out.println("<td height='30' class='pdn_mainHD'>"+m_header_name+"</td>"); 
			out.println("</tr>"); 
			out.println("<tr> "); 
			out.println("<td height='1'><img src='spacer.gif' width='1' height='1'></td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td style='height: 327px'>"); 
			out.println("<table class='table' border='0' cellpadding='0' cellspacing='0' height='100%' width='100%'>   "); 
			out.println("<tr>"); 
			out.println("<td height='1'><img height='1' src='spacer.gif' width='1' /></td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td align='left' class='pdn_txtpos2' style='height: 18px' id='help_box'> Credit Process - Assign Debtors to Client Facility</td>"); 
			out.println("</tr>"); 
			out.println("<tr>"); 
			out.println("<td  height='10px' class='pdn_txtpos'>"); 
			out.println("<table class='table' cellpadding='2' cellspacing='2' border='0'> "); 
			out.println("<tr>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"New\");' onclick='load_screen_status(\"NEW\")' value=\"New\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Edit\");' onClick='load_screen_status(\"EDIT\")' value=\"Edit\"></td>");  
			//out.println("<td width='10%' align='center'></td>");
			//out.println("<td width='10%' align='center'></td>");
			out.println("<td width='6%'></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Save\");'  onClick='save_window()' value=\"Save\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Help\");' onClick='load_screen_status(\"HELP\")' value=\"Help\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Cancel\");'  onclick='clear_window()' value=\"Cancel\"></td>");  
			out.println("<td width='10%' align='center'><input type=\"button\" class='mainbut' onMouseout='load_roll_out_value();' onMouseOver='load_roll_value(\"Close\");'  onclick='close_window()' value=\"Close\"></td>"); 
			out.println("<td width='*%' align='right' class='div_input'></td></tr>");  
			out.println("</table>");  
			out.println("</td></tr><tr>");  
			out.println("<td class='line' height='1'><img height='1' src='spacer.gif' width='1' /></td>");  
			out.println("</tr><tr>");  
			out.println("<td class='pdn_txtpos' height='150' valign='top'>");  
			
			out.println("<br>");
			
			out.println("<table align='center' width='100%' class='table'>"); 
			out.println("<tr>"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_FACILITY_NO'  class=div_input>Facility No *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_FACILITY_NO' maxlength='20' size='10' onblur=\"help_update_facility()\">"); 
			out.println("<input class='but_input' type='button' name='BUT_HELP_MAIN_1' value=\"Help\" onClick=\"help_update_facility()\"></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_CODE'  class=div_input>Client Code	</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_CODE' maxlength='10' size='10' disabled>"); 
			out.println("<input class='but_input' type='button' name='BUT_HELP_MAIN' value=\"Details\" onClick=\"show_client(document.Form1.TXT_CLIENT_CODE.value)\"></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_DESC'  class=div_input>Client Name</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_NAME' maxlength='10' size='50' style='width:200' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_FACILITY_MANAGER_NAME'  class=div_input>Facility Manager Name*</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_FACILITY_MANAGER_NAME' maxlength='50' size='50'  style='width:200' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_TOT_CREDIT_LIMIT'  class=div_input>Total Facility Credit Limit</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_TOT_CREDIT_LIMIT' maxlength='25' size='50' style='width:200;text-align:right;'  onchange=format_num(document.Form1.TXT_CREDIT_LIMIT,4) disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");	
			out.println("</table>");

			out.println("<hr>");
			
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_DEBTOR_CODE'  class=div_input>Debtor Code *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_DEBTOR_CODE' maxlength='10' size='10' onblur=\"help_update_client()\">"); 
			out.println("<input class='but_input' type='button' name='BUT_DEBTOR_MAIN' value=\"Help\" onClick=\"help_update_client()\">");
			out.println("<input class='but_input' type='button' name='BUT_DEBTOR_MAIN' value=\"Details\"  onClick=\"show_client(document.Form1.TXT_DEBTOR_CODE.value)\"></td>");
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_DEBTOR_DESC'  class=div_input>Debtor Name</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_DEBTOR_NAME' maxlength='10' size='50' style='width:200' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_MMGR'  class=div_input>Debtor Mkt. Executive *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_MMGR' maxlength='50' size='50'><input class=\"but_input\" type=\"button\" name=\"BUT_CLIENT_MGT\" value=\"Help\" onClick=\"help_client_manager()\"></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_MMGR_NAME'  class=div_input>Debtor Mkt. Executive Name*</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_MMGR_NAME' maxlength='50' size='50'  style='width:200' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_DESIG_PAYMENT'  class=div_input>Debtor Designation Payment </DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_DESIG_PAYMENT' maxlength='50' size='50'  style='width:300'></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CLIENT_CONT_PERSON'  class=div_input>Debtor Contact Person </DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CLIENT_CONT_PERSON' maxlength='200' size='200' style='width:200' ></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("</table>");
			
			out.println("<table align='center' width='100%' class='table'>"); 
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CREDIT_LIMIT'  class=div_input>Debtor Credit Limit *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CREDIT_LIMIT' maxlength='25' size='50' style='width:200;text-align:right;'  onchange=format_num(document.Form1.TXT_CREDIT_LIMIT,4)></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");	
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_CREDIT_PERIOD'  class=div_input>Debtor Credit Period *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_CREDIT_PERIOD' maxlength='25' size='50' style='width:200;text-align:right;'  onchange=format_num(document.Form1.TXT_CREDIT_PERIOD,4)></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_TOL_CREDIT_PERIOD'  class=div_input>Debtor Tolerance Credit Period *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_TOL_CREDIT_PERIOD' maxlength='25' size='50' style='width:200;text-align:right;' onchange=format_num(document.Form1.TXT_TOL_CREDIT_PERIOD,4)></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_RES_MARGIN'  class=div_input>Debtor Reserve Margin Value (%) *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_RES_MARGIN' maxlength='25' size='25' style='width:200;text-align:right;' onchange=format_num(document.Form1.TXT_RES_MARGIN,4)></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("</table>"); 
			
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_PRODUCT_CODE'  class=div_input>Product Package Code *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_PRODUCT_CODE' maxlength='10' size='10' onblur=\"help_update_product()\" disabled>"); 
			out.println("<input class='but_input' type='button' name='BUT_HELP_MAIN' value=\"Help\" onClick=\"help_update_product()\" disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_PRODUCT_DESC'  class=div_input>Product Package Description </DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_PRODUCT_DESC' maxlength='50' size='50' style='width:300' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<table>");
			
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_PRODUCT_MAIN_ADD\" value=\"Add\" onClick=\"add_products()\" disabled></td>"); 
			out.println("<td width='40%' ></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<table>");
			
			out.println("<table>"); 
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='100%'><DIV id='product_detail_data'  class=div_input></DIV></td>");
			out.println("</tr>");
			out.println("</table>"); 
			
			out.println("<br>"); 
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_FEE_CODE'  class=div_input>Fee Package Code *</DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_FEE_CODE' maxlength='10' size='10' onblur=\"help_update_fee()\" disabled>"); 
			out.println("<input class='but_input' type='button' name='BUT_HELP_MAIN' value=\"Help\" onClick=\"help_update_fee()\" disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("<tr >"); 
			out.println("<td width='30%' ><DIV id='DIV_TXT_FEE_DESC'  class=div_input>Fee Package Description </DIV></td>"); 
			out.println("<td width='40%' ><input class='txt_input' type='text' name='TXT_FEE_DESC' maxlength='50' size='50' style='width:300' disabled></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("</table>"); 
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='30%' ><input class=\"but_input\" type=\"button\" name=\"BUT_HELP_FEE_MAIN_ADD\" value=\"Add\" onClick=\"add_fee()\" disabled></td>"); 
			out.println("<td width='40%' ></td>"); 
			out.println("<td width='*%'></td>"); 
			out.println("</tr>");
			out.println("</table>");
			
			out.println("<table>"); 
			out.println("<table align='center' width='100%' class='table'>");
			out.println("<tr>"); 
			out.println("<td width='100%'><DIV id='fee_detail_data'  class=div_input></DIV></td>");
			out.println("</tr>");
			out.println("</table>"); 
			
			out.println("<table align='center' width='100%'>"); 
			out.println("<tr>"); 
			out.println("<td width='100%' class='note'></td>"); 
			out.println("</tr>"); 
			out.println("</table>"); 
			out.println("</form>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/validate.js'></SCRIPT>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/factoring_drill_down.js'></SCRIPT>"); 
			out.println("<SCRIPT language1.2='JavaScript' src='"+m_html_client_url+"/ajax_data_gateway.js'></SCRIPT>"); 
			out.println("</body>"); 
			out.println("</html>"); 
			out.flush();
		}
		catch (Exception ex) {
			try{out.println("Error:"+ex.toString());
			}catch(Exception e){}
		}
		finally{
				if(out!=null){
				try{out.close();  
				}catch(Exception e){}
				}
		}
	}
}
