

import java.io.*; 
import javax.servlet.*; 
import javax.servlet.http.*; 
import java.sql.*; 
import java.util.*; 

//DEVELOPED BY MAHELA FOR OFSCL user guide on 24-05-2007

public class LAKDL_AF_UG_Collection extends javax.servlet.http.HttpServlet { 

	ServletOutputStream out = null;
	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
		 
		try { 
			 
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String header_name=m_sn_methods.header_name.trim();
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			out = res.getOutputStream(); 
			 
				out.println("<!doctype html public '-//w3c//dtd html 4.0 transitional//en'>");
				out.println("<html>");
				out.println("<link REL='STYLESHEET' HREF='"+m_html_client_url+"/css/Asset_Financing_System.css' TYPE=\"text/css\">"); 
				out.println("<head>");
				out.println("	<STYLE TYPE='text/css'> ");
				out.println("	a:link {color:black; text-decoration:none font-size: 12px; color: #ED0306;}");//
				out.println("	a:hover {color:red; text-decoration:underline font-size: 12px; color: #ED0306;} ");
				out.println("	a:active {color:blue; text-decoration:underline font-size: 12px; color: #ED0306;}");
				out.println(" </STYLE>");
				out.println("   <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
				out.println("   <meta name='Generator' content='Microsoft FrontPage 5.0'>");
				out.println("   <meta name='GENERATOR' content='Mozilla/4.7 [en] (Win98; I) [Netscape]'>");
				out.println("   <title>MIDDLE OFFICE</title>");
				out.println("</head>");
				out.println("<body text='#000000' bgcolor='#FFFFFF' link='#000000' vlink='#000000' alink='#000000'>");
		
				//----------------- Assign Collection Officer User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p class=ug_headin><a NAME='Assign_Collection_Officer'>");
				out.println("</a><u>Collection - Assign Collection Officer </u>");
				out.println(" ");
				out.println("<p class=rep-body>After the lease is activated, finance number will be given for a facility. Those facilities will be listed in this screen in order to assign a collection officer. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New");
				out.println("<p align='justify' class=rep-body>Officer can be selected from the help option which is there in front of the record. The record can be saved using the Save option.");
				out.println("<p align='justify' class=rep-body>Edit");
				out.println("<p align='justify' class=rep-body>Selected officer can be changed from this option and entry has to be saved again. ");
				
				//----------------- Receipts-Entry User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p class=ug_headin><a NAME='Receipts_Entry'>");
				out.println("</a><u>Collection - Receipts - Entry </u>");
				out.println(" ");
				out.println("<p class=rep-body>Settlement details will be entered from this section. When clients are making rental payments against the invoices raised by the Financing Company, those details will be recorded from section. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New");
				out.println("<p align='justify' class=rep-body>When entering a new record, Value date, amount, and reference number have to be entered. Client, Payer account number, settlement mode can be selected from the relevant help option. Upon selection of Payer account number Payer branch field automatically gets filled. Once all the records are entered record can be saved using the save option. Settlement code will be generated by the system. If there are cheque returns for the selected client, those details will be listed in the screen. Settlements can be allocated to invoices from this screen. If user doesn't wants to allocate invoices, can click on status and then entry can be saved. ");
				out.println("<p align='justify' class=rep-body>Edit");
				out.println("<p align='justify' class=rep-body>To modify an existing record settlement number has to be selected. After editing settlement details entry should be saved using the Save option. ");
				out.println("<p align='justify' class=rep-body>Delete");
				out.println("<p align='justify' class=rep-body>To delete an existing record settlement number has to be selected and entry should be saved using the Save option.");
		
				//----------------- Receipts- Invoice Allocation User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Invoice_Allocation'>");
				out.println("</a><u>Collection - Receipts - Invoice Allocation </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Receipts from clients can be allocated to a specific invoice from this section. Once the receipt is entered to the system from the settlement screen, system will allocate that receipt to existing outstanding invoices according to their due status. Latest one will be settled finally. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New");
				out.println("<p align='justify' class=rep-body>In order to allocate a new receipt user can select the client name first. Then all pending receipts and invoices will be displayed in the screen. If user wants he/she can change the initial allocations. ");
		
				//----------------- Receipts - Deposit User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Receipts_Deposit'>");
				out.println("</a><u>Collection - Receipts - Deposit </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Cheques and cash collected from clients have to be deposited in the bank and those records will be entered to the system from this section. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("<p><li class=rep-body>	Save</p>");
				out.println("<p><li class=rep-body>	Help</p>");
				out.println("<p><li class=rep-body>	Cancel</p>");
				out.println("<p><li class=rep-body>	Close</p>");
				out.println("<p><li class=rep-body>	Pending Receipts</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				out.println("<p align='justify' class=rep-body>Upon selection of cash or cheque under the settlement mode pending receipts will be listed on the screen. Account number of the bank which we are going to deposit cash or cheques has to be selected. User can select the collections which will be deposited on that day. After entering required details record can be saved. Settlement deposit code will be generated by the system.");
				out.println("<p align='justify' class=rep-body>Delete ");
				out.println("<p align='justify' class=rep-body>Settlement deposit code can be selected from the help option. Once the Settlement deposit code selected cheques or cash deposited with its bank details, amounts and receipt numbers will be shown. Entry can be saved using the save option.");
				out.println("<p align='justify' class=rep-body>View Pending Receipts ");
				out.println("<p align='justify' class=rep-body>All the pending receipts including cash and cheque which are not deposited in bank account can be seen.");
		
				//----------------- Receipts - Return & Realisation User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Receipts_Return_Realisation'>");
				out.println("</a><u>Collection - Receipts - Return & Realisation </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Return and realised status of the cheques deposited can be updated from this section. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("<p><li class=rep-body>	Save</p>");
				out.println("<p><li class=rep-body>	Help</p>");
				out.println("<p><li class=rep-body>	Cancel</p>");
				out.println("<p><li class=rep-body>	Close</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				out.println("<p align='justify' class=rep-body>Account number has to be selected from the Help option. Then bank and branch details will get filled. Numbers of the cheques deposited in the selected bank will be listed in the screen. User can mark the relevant tick box according realised or returned status. Today's date will be displayed as the returned/realised date and if user wants he/she can change the date. Then returns and realisations can be saved. Returned cheques will return to Settlement Deposit screen for deposit. ");
				out.println("<p align='justify' class=rep-body>Delete ");
				out.println("<p align='justify' class=rep-body>Account number has to be selected from the Help option. Then bank and branch details will get filled. Once a date range is given all the cheques realised within that date range will be listed in the screen. Delete option will help to return a cheque which was updated as realised. Once delete is saved, those cheques will return to initial screen. ");
		
				//----------------- Temporary Receipts Entry User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Temp_Receipt_Entry'>");
				out.println("</a><u>Collection - Temporary Receipts - Entry </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Temporary receipts will be issued when the collections are made by the recovery officers. These receipts have to be approved by the Collection Manager and once it is approved by the cashier receipt will become an original one. Details of Temporary receipts will be entered from this section. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("<p><li class=rep-body>	Deactivate</p>");
				out.println("<p><li class=rep-body>	Reactivate</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				out.println("<p align='justify' class=rep-body>In order to create new record user has to enter Finance number, amount, and date and cheque number. Branch code, Account no, Currency code, Receipt book no can be selected from the relevant Help option. Required fields are marked with a * on the screen. Then entry can be saved using the save option. Temporary Receipt number will be generated by the system.");
				out.println("<p align='justify' class=rep-body>Edit ");
				out.println("<p align='justify' class=rep-body>In order to modify a record user has to select the Temporary Receipt code. After modifying the details can save the record.");
				out.println("<p align='justify' class=rep-body>Deactivate ");
				out.println("<p align='justify' class=rep-body>In order to deactivate a record user has to select the Temporary Receipt code. Then all the details get filled and the details have to be saved using the save option.");
				out.println("<p align='justify' class=rep-body>Reactivate ");
				out.println("<p align='justify' class=rep-body>In order to reactivate a record user has to select the Temporary Receipt code. Then all the details get filled and the details have to be saved using the save option.");
				
				//----------------- Temporary Receipts Approval User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Temp_Receipt_Approval'>");
				out.println("</a><u>Collection - Temporary Receipts - Approval </u>");
				out.println(" ");
				//out.println("<p align='justify'>Temporary receipts will be issued when the collections are made by the recovery officers. These receipts have to be approved by the Collection Manager and once it is approved by the cashier receipt will become an original one. Details of Temporary receipts will be entered from this section. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				//out.println("<p><li>	Deactivate</p>");
				//out.println("<p><li>	Reactivate</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				//out.println("<p align='justify'>In order to create new record user has to enter Finance number, amount, and date and cheque number. Branch code, Account no, Currency code, Receipt book no can be selected from the relevant Help option. Required fields are marked with a * on the screen. Then entry can be saved using the save option. Temporary Receipt number will be generated by the system.");
				out.println("<p align='justify' class=rep-body>Delete ");
				//out.println("<p align='justify'>In order to modify a record user has to select the Temporary Receipt code. After modifying the details can save the record.");
				
				//----------------- Post Dated Cheques Entry User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Post_Dated_Cheques'>");
				out.println("</a><u>Collection - Post Dated Cheques - Entry </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>This option can be used to record details of post dated cheques in the system till deposit those cheques. Add option can be used when there are more than one cheque.");
				
				//----------------- Post Dated Cheques Receipt-Generation User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Post_Dated_Cheques_Receipt_Gen'>");
				out.println("</a><u>Collection - Post Dated Cheques - Receipt Generation </u>");
				out.println(" ");
				//out.println("<p align='justify'>This option can be used to record details of post dated cheques in the system till deposit those cheques. Add option can be used when there are more than one cheque.");
				
				//----------------- Vehicle Inventory User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Vehicle_Inventory'>");
				out.println("</a><u>Collection - Repossesion - Vehicle Inventory </u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>This option caters to add vehicle to the vehicle inventory. After selecting the relevant application number and the vehicle number, check list should be completed through the system and saved. Edit existing vehicle details or Delete can be done through vehicle inventory option.");
				
				//----------------- Vehicle Inventory Approval User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Vehicle_Inventory_Approval'>");
				out.println("</a><u>Collection - Repossesion - Vehicle Inventory Approval</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Approval can be done for vehicles added through Entry of Vehicle Inventory screen.");
				
				//----------------- Repossesion Advertisements User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Advertisements'>");
				out.println("</a><u>Collection - Repossesion - Advertisements</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Repossessed vehicles will be sold to a third party .To sell those vehicles company will publish an advertisement in a newspaper. Advertisement for a repossessed vehicle can be generated from this screen. This section consists of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				out.println("<p align='justify' class=rep-body>In order to generate a new advertisement Inventory number has to be selected from the Help option and assigned vehicle numbers for that Inventory number can be selected from the next help option. User can enter the date and amount. Record can be saved using the Save option.");
				out.println("<p align='justify' class=rep-body>Edit ");
				out.println("<p align='justify' class=rep-body>In order to modify an existing record user has to select an advertisement number from the Help option. Then other data get filled. After modifying the data user has to save the data using Save option.");
				out.println("<p align='justify' class=rep-body>Delete ");
				out.println("<p align='justify' class=rep-body>To delete an advertisement user has to select an advertisement number from the Help option. Then other data get filled. To delete user has to save the data using Save option.");
				
				//----------------- Entry Of Offers User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Entry_Of_Offers'>");
				out.println("</a><u>Collection - Repossesion - Entry Of Offers</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Offer/Offers for an advertisement can be recorded through this option.");
				
				//----------------- Acceptance Of Offers User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Acceptance_Of_Offers'>");
				out.println("</a><u>Collection - Repossesion - Acceptance Of Offers</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Recorded offers for an advertisement can be accepted through Acceptance of Offer screen.");
				
				//----------------- Recovery of Financed Amount User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Recovery_Of_Financed_Amount'>");
				out.println("</a><u>Collection - Repossesion - Recovery Of Financed Amount</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>If there is a balance which is not recovered after reselling the repossessed vehicle company can make a decision whether to take Legal actions or to a raise a Credit note. One of the options can be selected and have the facility to keep a record of legal actions or to raise a Credit Note.");
				out.println("<p align='justify' class=rep-body>Once the Credit note is selected, system will take user to the Invoice Adjustments screen. Invoices which are not settled and the adjusted date can be selected. Once the record is saved balance gets adjusted.");
				out.println("<p align='justify' class=rep-body>To record legal actions that has to be selected first and from the next screen details about the lawyers.");
				
				//----------------- Legal Actions - Assignments User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Legal_Action_Assign'>");
				out.println("</a><u>Collection - Legal Actions - Assignments</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Result of legal cases will be documented through this section. Legal number can be selected from the help option then the case date will be appeared. User has to enter decision of the case, next courts date and the documents required. Save option will save the record.");
				
				//----------------- Legal Activities - Entry User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Legal_Activities_Entry'>");
				out.println("</a><u>Collection - Legal Activities - Entry</u>");
				out.println(" ");
				out.println("<p align='justify' class=rep-body>Asset Financing company will take Legal action if they cannot locate the vehicle or unable to cover the outstanding value of the facility after reselling the vehicle. Details of legal cases will be entered to the system from this section. This section comprises of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				out.println("<p align='justify' class=rep-body>In order to enter a new record Finance number can be selected from the relevant Help option. Then Client code, Client Name, Legal position and Finance due amount will get filled automatically. Lawyer code can select from the help option. User can fill other details and can save the entry.");
				out.println("<p align='justify' class=rep-body>Edit ");
				out.println("<p align='justify' class=rep-body>To modify an existing record Legal number can be selected from the Help option. Then all the details get filled. After altering the data record has to be saved again.");
				out.println("<p align='justify' class=rep-body>Delete ");
				out.println("<p align='justify' class=rep-body>After selecting a Legal number user can save the entry.");
				
				//----------------- Repossesion Order User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Repossesion_Order'>");
				out.println("</a><u>Collection - Repossesion Order</u>");
				out.println(" ");
				//out.println("<p align='justify'>Asset Financing company will take Legal action if they cannot locate the vehicle or unable to cover the outstanding value of the facility after reselling the vehicle. Details of legal cases will be entered to the system from this section. This section comprises of following options.");
				out.println("<blockquote>");
				out.println("<p><li class=rep-body>	New</p>");
				out.println("<p><li class=rep-body>	Edit</p>");
				out.println("<p><li class=rep-body>	Delete</p>");
				out.println("</blockquote>");
				out.println("<p align='justify' class=rep-body>New ");
				//out.println("<p align='justify'>In order to enter a new record Finance number can be selected from the relevant Help option. Then Client code, Client Name, Legal position and Finance due amount will get filled automatically. Lawyer code can select from the help option. User can fill other details and can save the entry.");
				out.println("<p align='justify' class=rep-body>Edit ");
				//out.println("<p align='justify'>To modify an existing record Legal number can be selected from the Help option. Then all the details get filled. After altering the data record has to be saved again.");
				out.println("<p align='justify' class=rep-body>Delete ");
				//out.println("<p align='justify'>After selecting a Legal number user can save the entry.");
				
				//----------------- Deletion Letter - CMT User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Deletion_Letter'>");
				out.println("</a><u>Collection - Deletion Letter-CMT</u>");
				out.println(" ");
				//out.println("<p align='justify'>Result of legal cases will be documented through this section. Legal number can be selected from the help option then the case date will be appeared. User has to enter decision of the case, next courts date and the documents required. Save option will save the record.");
				
				//----------------- Thanking Letter - Client User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Thanking_Letter_Client'>");
				out.println("</a><u>Collection - Thanking Letter - Client</u>");
				out.println(" ");
				//out.println("<p align='justify'>Result of legal cases will be documented through this section. Legal number can be selected from the help option then the case date will be appeared. User has to enter decision of the case, next courts date and the documents required. Save option will save the record.");
				
				//----------------- Thanking Letter - Introducer User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
				
				out.println("<p align='justify' class=ug_headin><a NAME='Thanking_Letter_Introducer'>");
				out.println("</a><u>Collection - Thanking Letter - Introducer</u>");
				out.println(" ");
				//out.println("<p align='justify'>Result of legal cases will be documented through this section. Legal number can be selected from the help option then the case date will be appeared. User has to enter decision of the case, next courts date and the documents required. Save option will save the record.");
		
				out.println("</body>");
				out.println("</html>");
				out.flush();
				
		}
		catch (Exception ex) {
			try{out.println("Error:"+ex.toString());}catch(Exception e){}
		}
		finally{
				if(out!=null){try{out.close();  }catch(Exception e){}}
		}
	}
}
