

import java.io.*; 
import javax.servlet.*; 
import javax.servlet.http.*; 
import java.sql.*; 
import java.util.*; 

//DEVELOPED BY MAHELA FOR OFSCL user guide on 24-05-2007

public class LAKDL_AF_UG_Invoicing extends javax.servlet.http.HttpServlet { 

	ServletOutputStream out = null;
	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
		 
		try { 
			 
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String header_name=m_sn_methods.header_name.trim();
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			out = res.getOutputStream(); 
			 
						out.println("<!doctype html public '-//w3c//dtd html 4.0 transitional//en'>");
						out.println("<html>");
						out.println("<link REL='STYLESHEET' HREF='"+m_html_client_url+"/css/Asset_Financing_System.css' TYPE=\"text/css\">"); 
						out.println("<head>");
						out.println("	<STYLE TYPE='text/css'> ");
						out.println("	a:link {color:black; text-decoration:none font-size: 12px; color: #ED0306;}");//
						out.println("	a:hover {color:red; text-decoration:underline font-size: 12px; color: #ED0306;} ");
						out.println("	a:active {color:blue; text-decoration:underline font-size: 12px; color: #ED0306;}");
						out.println(" </STYLE>");
						out.println("   <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
						out.println("   <meta name='Generator' content='Microsoft FrontPage 5.0'>");
						out.println("   <meta name='GENERATOR' content='Mozilla/4.7 [en] (Win98; I) [Netscape]'>");
						out.println("   <title>MIDDLE OFFICE</title>");
						out.println("</head>");
						out.println("<body text='#000000' bgcolor='#FFFFFF' link='#000000' vlink='#000000' alink='#000000'>");
						
						//----------------- Invoicing -  Invoices Generation  ------------------------------------------------------------------------------------------------------------------------------------------------
						
						out.println("<p class=ug_headin><a NAME='Invoices_Gen'></a><u>Invoicing - Invoices Generation</u> ");
						out.println("<p align='justify' class=rep-body>Invoices can be generated from this section. In this screen last invoice cycle will be displayed. Next invoice cycle can be set and can press proceed button to print Invoices. Once the finance activation is done. Exceptions can be generated by selecting Run Invoice Routine option without changing dates of the Invoice Cycle.");
						
						//----------------- Invoicing -  Payment Requisition Special Approval  ------------------------------------------------------------------------------------------------------------------------------------------------
						
						out.println("<p class=ug_headin><a NAME='Invoices_Printing'></a><u>Invoicing - Invoices Printing</u> ");
						out.println("<p align='justify' class=rep-body>Generated invoices can be printed and sent to the client. Invoices will be grouped under the Finance number. ");

						//----------------- Invoicing - Invoices Other ------------------------------------------------------------------------------------------------------------------------------------------------
						
						out.println("<p class=ug_headin><a NAME='Invoices_Other'>");
						out.println("</a><u>Invoicing - Invoices - Other </u>");
						out.println(" ");
						out.println("<p align='justify' class=rep-body>Invoices other than rental invoices will be fed to the system through other Invoices. This section consists of following options.");
						out.println("<blockquote>");
						out.println("<p><li class=rep-body>	New</p>");
						out.println("<p><li class=rep-body>	Edit</p>");
						out.println("<p><li class=rep-body>	Delete</p>");
						out.println("</blockquote>");
						out.println("<p align='justify' class=rep-body>New");
						out.println("<p align='justify' class=rep-body>Invoice type can be selected from the drop down menu. Finance number, date can be selected and net vat amounts can be entered. The record can be saved using the Save option."); 
						out.println("<p align='justify' class=rep-body>Edit");
						out.println("<p align='justify' class=rep-body>Modifications to the existing invoice can be done through Edit option. After doing the necessary changes entry can be saved.");
						out.println("<p align='justify' class=rep-body>Delete");
						out.println("<p align='justify' class=rep-body>To delete an existing invoice, invoice number has to be selected and entry should be saved using the Save option.");
						
						out.println("</body>");
						out.println("</html>");
						out.flush();
		}
		catch (Exception ex) {
			try{out.println("Error:"+ex.toString());}catch(Exception e){}
		}
		finally{
				if(out!=null){try{out.close();  }catch(Exception e){}}
		}
	}
}
