

import java.io.*; 
import javax.servlet.*; 
import javax.servlet.http.*; 
import java.sql.*; 
import java.util.*; 

//DEVELOPED BY MAHELA FOR OFSCL user guide on 24-05-2007

public class LAKDL_AF_UG_FollowUp_new extends javax.servlet.http.HttpServlet { 

	ServletOutputStream out = null;
	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
		 
		try { 
			 
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String header_name=m_sn_methods.header_name.trim();
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			out = res.getOutputStream(); 
			 
						out.println("<!doctype html public '-//w3c//dtd html 4.0 transitional//en'>");
						out.println("<html>");
						out.println("<link REL='STYLESHEET' HREF='"+m_html_client_url+"/css/Asset_Financing_System.css' TYPE=\"text/css\">"); 
						out.println("<head>");
						out.println("	<STYLE TYPE='text/css'> ");
						out.println("	a:link {color:black; text-decoration:none font-size: 12px; color: #ED0306;}");//
						out.println("	a:hover {color:red; text-decoration:underline font-size: 12px; color: #ED0306;} ");
						out.println("	a:active {color:blue; text-decoration:underline font-size: 12px; color: #ED0306;}");
						out.println(" </STYLE>");
						out.println("   <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
						out.println("   <meta name='Generator' content='Microsoft FrontPage 5.0'>");
						out.println("   <meta name='GENERATOR' content='Mozilla/4.7 [en] (Win98; I) [Netscape]'>");
						out.println("   <title>MIDDLE OFFICE</title>");
						out.println("</head>");
						out.println("<body text='#000000' bgcolor='#FFFFFF' link='#000000' vlink='#000000' alink='#000000'>");
						
						//----------------- Follow Up User Guide ------------------------------------------------------------------------------------------------------------------------------------------------
						
						
						out.println("<p align='justify' class=ug_headin><a NAME='FollowupHeader'>");
						out.println("</a><u>Follow Up </u>");
						out.println(" ");
						out.println("<p align='justify' class=rep-body>Follow up sub module is a sub section that is linked with every other module. You can enter follow-ups, assign to one or many of your subordinates and view status when the assigned people update new status. ");

						out.println("<p align='justify' class=ug_headin><a NAME='Entry'>");
						out.println("</a><u>Entry</u>");
						out.println(" ");
						//out.println("<p align='justify'>Asset Financing company will take Legal action if they cannot locate the vehicle or unable to cover the outstanding value of the facility after reselling the vehicle. Details of legal cases will be entered to the system from this section. This section comprises of following options.");
						out.println("<p align='justify' class=rep-body>	Other than automatic follow ups that are generated by the system from the activities you carry out, you are facilitated to enter tasks manually and assign users to follow up those tasks. When you enter a follow up entry through this screen, it appears to the user who you assign as a task to be carried out.");
						
						
						out.println("</body>");
						out.println("</html>");
						out.flush();
		}
		catch (Exception ex) {
			try{out.println("Error:"+ex.toString());}catch(Exception e){}
		}
		finally{
				if(out!=null){try{out.close();  }catch(Exception e){}}
		}
	}
}
