// Delevery Order
// File Generated By ns on 06-10-2011 


import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*; 
import java.util.*;
import oracle.jdbc.driver.*;

public class LAKDL_AF_CR_PRO_Delivery_Order extends javax.servlet.http.HttpServlet { 

	public synchronized void service(HttpServletRequest req, HttpServletResponse res)  throws IOException { 
	
	ServletOutputStream out  = null;
	Connection          conn = null;
	Statement           stmt = null;
	ResultSet    rs;
 	//public String m_html_client_url,reqstr,m_Letter_date,m_c_code,m_add1,m_add2,m_name,m_city_desc,m_due_date,m_no_of_due_date,m_finance_no,m_print;
	double m_amount_due;
	java.text.NumberFormat nf=null;
		 
		try { 
		
			LAKDL_AF_CO_conn_methods m_sn_methods = new LAKDL_AF_CO_conn_methods(); 
			conn = m_sn_methods.met_user_validate(req); 
			String m_html_client_url=m_sn_methods.html_client_url.trim(); 
			String m_class_url=m_sn_methods.servlet_client_url.trim()+":"+m_sn_methods.client_t3_port.trim(); 
			String m_fschema_name=m_sn_methods.client_name.trim();
			String m_schema_name = m_sn_methods.schema_name.trim();
		    
			res.setStatus(HttpServletResponse.SC_OK); 
			res.setContentType("text/html"); 
			out = res.getOutputStream(); 
			
			nf = java.text.NumberFormat.getInstance(Locale.US);
			nf.setMinimumFractionDigits(2);
			nf.setMaximumFractionDigits(2);
			
			String m_chksql = req.getParameter("chksql");
			
			if(m_chksql.trim().equals("main_page")){
			
			stmt = conn.createStatement ();
			
			String m_purch_order_no    =req.getParameter("pur_ord_no");	 
			String m_print            =req.getParameter("print");	 
			
			//Decaring variables
			String m_sts="";
			String m_status="";
			String m_Letter_date="";
			//String m_print="";
			String m_client_code="";
			String m_full_name="";
			String m_add1="";
			String m_add2="";
			String m_city_name="";
			String m_title="";
			String m_type=""; 
			String m_company_name="";
			String m_ven_name="",m_ven_add="",m_ven_city="",m_ven_type="";
			String m_Amount_wd=""; 
			String m_Qty2=""; //Added by Chandana on 26/08/2010
			String m_Eng_no="";
			String m_Chas_no="";
			String m_Reg_no="";
			String m_Color="";
			String m_Descr="";
			String m_Extras="";
			String m_finance_no="";
			String m_vendor_code="";
			String m_branch_code="";
			String m_approved_user="";
			String mm_rubber_seal_string="";
			String m_address1="";
			String m_address2="";
			String m_address_name="";
			String m_address="";
			String m_ter_date="";
			
			/*String m_full_name="";
			String m_add1="";
			String m_add2="";
			String m_city_name="";
			String m_title="";
			String data="";
			String m_address1="";
			String m_address2="";
			String m_address_name="";
			String m_approved_user="";
			*/
			int m_data_count=0;
			
			double m_Net_Amt=0;
			double m_Qty=0; //Added by Chandana on 26/08/2010
			double m_tot_amt=0; //Added by Chandana on 26/08/2010
			
			rs=stmt.executeQuery("SELECT DISTINCT TO_CHAR(SYSDATE,'DD-MON-YY') SYS_DATE , NVL(A.FINANCE_NO,'-') FINANCE_NO "+
				" ,DECODE(B.PRINTED_STATUS,'N','ORIGINAL','Y','COPY') PRINTED_STATUS, B.VENDER_CODE VENDER_CODE, B.BRANCH_CODE BRANCH_CODE "+
				" ,A.CLIENT_CODE CLIENT_CODE,NVL(B.APPROVED_USER,'OFSCLALL') APPROVED_USER "+
				" FROM  "+m_schema_name+".AF_CO_PRO_APPLICATION_DETAILS A , "+m_schema_name+".AF_CR_PRO_PURCHASE_ORDER B "+
				" WHERE A.APPLICATION_NO=B.APPLICATION_NO "+
				" AND   PURCHASE_ORDER_NO='"+m_purch_order_no+"' ");
				
				if(rs.next()){
				m_Letter_date    = rs.getString("SYS_DATE");
				m_finance_no     = rs.getString("FINANCE_NO");
				m_status         = rs.getString("PRINTED_STATUS");
				m_vendor_code    = rs.getString("VENDER_CODE");
				m_branch_code    = rs.getString("BRANCH_CODE");
				m_client_code    = rs.getString("CLIENT_CODE");
				m_approved_user  = rs.getString("APPROVED_USER");
				}
				
				rs = stmt.executeQuery(" SELECT "+
				" NVL(UPPER(COMPANY_NAME),' ')  COMPANY_NAME "+
				" FROM "+m_schema_name+".AF_CO_MAS_COMPANY_DETAILS ");
				
				if(rs.next()){
				m_company_name=rs.getString("COMPANY_NAME");
				}
															
				//modifed the above comment query by nuwan de silva on 18-11-2010
				String sql= "  SELECT SUB_MODEL_CODE,NVL(ENGINE_NO,'-'), "+
				" NVL(CHASSIS_NO,'-'),NVL(REG_NO,'-'), "+
				" QTY,X.MODEL_DESC,X.EXTRAS,SUM(X.NET_AMOUNT) "+
				" FROM (SELECT DISTINCT A.APPLICATION_NO,A.ENGINE_NO,A.CHASSIS_NO,A.REG_NO,C.QTY,C.SUB_MODEL_CODE,C.MODEL_CODE, "+
				" INITCAP(G.MAKE_DESC||' '||F.DESCRIPTION ||' '||E.DESCRIPTION) MODEL_DESC, "+  
				" NVL(EXTRAS_INCLUDED,'NIL') EXTRAS, "+  
				" "+m_schema_name+".AF_CO_GET_ASSET_NET_AMOUNT(A.APPLICATION_NO,A.INVOICE_NO) NET_AMOUNT,INVOICE_NO "+ 
				" FROM "+m_schema_name+".AF_CO_PRO_APP_INVOICE_DETAILS A , "+
				" "+m_schema_name+".AF_CO_PRO_APP_ASSET_DETAILS C, "+
				" "+m_schema_name+".AF_CO_MAS_MODEL D, "+
				" "+m_schema_name+".AF_CO_MAS_ITEM_SUB_CATEGORY E, "+
				" "+m_schema_name+".AF_CO_MAS_SUB_MODLE F, "+
				" "+m_schema_name+".AF_CO_MAS_MAKE G, "+
				" "+m_schema_name+".AF_CR_PRO_PURCHASE_ORDER H "+
				" WHERE A.APPLICATION_NO=H.APPLICATION_NO AND "+
				" H.VENDER_CODE    =A.VENDOR_CODE AND "+
				" A.ASSET_ID=C.ASSET_ID AND "+
				" C.ACTIVE_STATUS='Y' AND "+
				" A.ACTIVE_STATUS='Y' AND "+
				" C.MODEL_CODE = D.MODEL_CODE AND "+
				" D.ITEM_SUB_CAT = E.ITEM_SUB_CAT AND "+
				" F.SUB_CODE=A.SUB_MODEL_CODE AND "+
				" D.MAKE_CODE=G.MAKE_CODE AND "+
				" H.PURCHASE_ORDER_NO ='"+m_purch_order_no+"' "+
				" ) X, "+
				" "+m_schema_name+".AF_CO_MAS_SUB_MODLE Y "+
				" WHERE Y.SUB_CODE = X.SUB_MODEL_CODE "+
				" GROUP BY SUB_MODEL_CODE,NVL(ENGINE_NO,'-'),NVL(CHASSIS_NO,'-'),NVL(REG_NO,'-'), QTY,X.MODEL_DESC,X.EXTRAS ";														
							
			  out.println("<html><head>"); 
				out.println("<title>Delivery Order</title></head>");
				out.println("<link href=\""+m_html_client_url+"/css/Asset_Financing_System.css\" rel=\"stylesheet\" type=\"text/css\" >");
			 	out.println("<script>");
			
				out.println("function save_data(){");
				out.println("	m_url = \""+m_class_url+"/"+m_fschema_name+"AF_CR_PRO_Save_Purchase_Order_View_Letter?chksql=save_page&scr_name=AF_CR_PRO_PURCHASE_ORDER&vendor_code="+m_vendor_code+"&status="+m_status+"&app_no=&print="+m_print+"&pur_ord_no="+m_purch_order_no+"&client_code="+m_client_code+"&scr_type=DEL_ORD&branch_code="+m_branch_code+"\";"); //Modified by Sandun on 15-06-2009
				//out.println("	m_url = \""+m_class_url+"/"+m_fschema_name+"AF_CR_PRO_Save_Purchase_Order_View_Letter?chksql=save_page&scr_name=AF_CR_PRO_PURCHASE_ORDER&pur_ord_no="+m_purch_order_no+"\";"); 
				out.println(" window.location.href=m_url;"); 
				out.println("m_table.innerHTML=\"\" ");
				out.println("window.print();");
				out.println("}");
					
				out.println("function add_button(){");
				if (m_print.trim().equals("FALSE")){
				out.println("m_table.innerHTML=\"\" ");
				}
				else
				{
				out.println("m_writedata='<tr><td width=\"*%\" align=\"right\"><input class=\"but_input\" type=\"button\" name=\"BUT_PRINT\" value=\"Print\" onClick=\"save_data()\"></td></tr>';"); 
				out.println("m_table.innerHTML='<table align=\"center\" width=\"100%\" class=\"table\" border=\"0\">'+");
				out.println("m_writedata+'</table>';");
				} 
				out.println("}");
			
				out.println("</script>");
				out.println("<body bgcolor='white' leftmargin='0' topmargin='0' class=body onLoad=\"add_button()\">");
				//out.println("<blockquote>");
				
				out.println("<form name='Form1'>");
				out.println("<input type='hidden' name='hid_purch_order' VALUE=\"\">");
				

				out.println("<table align='center' width='100%' class='table'>"); 
				out.println("<tr>");  
				out.println("<td width=\"100%\"><DIV ID='m_table'></DIV></td>");
				out.println("</tr>"); 
				out.println("</table>");
				
				//Empty Table to Incease Gap
				out.println("<table border='0' width='100%' class='table'><tr><td height='80px;'></td></tr></table>"); 		
				
				out.println("<table border='0' width='100%' class='table'><tr><td height='610px;' valign='top'>"); 			
        
				
				rs = stmt.executeQuery(" SELECT "+
				" NVL(UPPER(TITLE),' ') TITLE, "+
				" NVL(UPPER(FULL_NAME),' ') FULL_NAME , "+ 
				" REPLACE(REPLACE(NVL(UPPER(ADDRESS1),' '),'-',' '),'NULL',' ') ADDRESS1,"+ 
				" REPLACE(REPLACE(NVL(UPPER(ADDRESS2),' '),'-',' '),'NULL',' ') ADDRESS2,"+ 
				" UPPER("+m_schema_name+".AF_CO_GET_CITY_NAME(CITY_CODE)) CITY_NAME "+ 
				" ,CLIENT_TYPE "+
				" FROM "+m_schema_name+".AF_CO_MAS_CLIENT "+
				" WHERE UPPER(CLIENT_CODE)=UPPER('"+m_client_code+"')");
				
				if(rs.next()){
				m_title=rs.getString(1);
				m_full_name=rs.getString(2);
				m_add1=rs.getString(3);
				m_add2=rs.getString(4);
				m_city_name=rs.getString(5);
				m_type=rs.getString(6);
				}
				
				if(m_city_name==null){
				m_city_name="";
				}if(m_add1.equals("-")){
				m_add1="";
				}if(m_add2.equals("-")){
				m_add2="";
				} if(!m_add1.equals(" ")){
				m_add1=m_add1+",";
				}if(!m_add2.equals(" ") && !m_city_name.equals("")){
				m_add2=m_add2+",";
				}else
				{m_add2=m_add2;
				}
				
				rs = stmt.executeQuery (" SELECT "+
				" NVL(UPPER(B.NAME), ' ' ) NAME, "+
				" NVL(UPPER(A.ADDRESS), ' ') ADDRESS, "+
				" NVL(UPPER("+m_schema_name+".AF_CO_GET_CITY_NAME(A.CITY_CODE)), ' ' ) CITY_NAME "+
				" ,NVL(UPPER(TYPE),'-') TYPE  "+
				" FROM "+m_schema_name+".AF_CO_MAS_VENDOR_LOCATION A, "+m_schema_name+".AF_CO_MAS_VENDORS B "+
				" WHERE UPPER(A.VENDOR_CODE)=UPPER(B.VENDOR_CODE) "+
				" AND UPPER(A.VENDOR_CODE) =UPPER('"+m_vendor_code+"') "+
				" AND UPPER(A.BRANCH)=UPPER('"+m_branch_code+"') "+
				" ");
				
				if(rs.next()){
				m_ven_name=rs.getString(1);
				m_ven_add=rs.getString(2);
				m_ven_city=rs.getString(3);
				m_ven_type=rs.getString(4);
        }
				
				
				rs = stmt.executeQuery(" SELECT "+
				" NVL(UPPER(DECODE(B.CLIENT_TYPE,'I',INITCAP(B.TITLE) || '. ' || B.FULL_NAME,'C','Mess' || '. '  || B.FULL_NAME)), '-' ), "+ //3
				" UPPER(NVL(DECODE(B.CLIENT_TYPE,'I',B.ADDRESS1,'C',B.REGISTERED_ADDRESS1),'-')), "+//4 //REGISTERED_ADDRESS1 //modified by nuwan de silva on 29-06-2010
				" UPPER(NVL(DECODE(B.CLIENT_TYPE,'I',B.ADDRESS2,'C',B.REGISTERED_ADDRESS2),'-')), "+//5 //REGISTERED_ADDRESS2 //modified by nuwan de silva on 29-06-2010
				//" UPPER(NVL(DECODE(B.CLIENT_TYPE,'I',NVL(UPPER("+m_schema_name+".AF_CO_GET_CITY_NAME(CITY_CODE)), '-' ),'C',NVL(UPPER("+m_schema_name+".AF_CO_GET_CITY_NAME(REGISTERED_CITY_CODE)), '-' )),'-')), "+//5 //REGISTERED_ADDRESS2
				" NVL(UPPER("+m_schema_name+".AF_CO_GET_CITY_NAME(CITY_CODE)), '-' ) , "+
				" B.CLIENT_TYPE ,"+
				" A.FINANCE_NO "+
				//" NVL(A.TER_TYPE,'-'), "+
				//" NVL(TO_CHAR(A.TER_TYPE_ENT_DATE,'DD-MM-YYYY'),'-') "+
				" FROM "+m_schema_name+".AF_CO_PRO_APPLICATION_DETAILS A,"+m_schema_name+".AF_CO_MAS_CLIENT B "+
				" WHERE A.CLIENT_CODE=B.CLIENT_CODE AND "+
				" A.FINANCE_NO=UPPER('"+m_finance_no+"')");
			  
				//more = rs.next();		
				
			  if(rs.next()){
				m_full_name=rs.getString(1);
				m_add1=rs.getString(2);
				m_add2=rs.getString(3);
				m_city_name=rs.getString(4);
				m_type=rs.getString(5);
				m_finance_no=rs.getString(6);
			  //m_ter_type  = rs.getString(7);
				//m_ter_date  = rs.getString(8);
				}
			
				if(!m_full_name.equals("-") && !m_add1.equals("-") && !m_add2.equals("-") && !m_city_name.equals("-") ){
				//m_full_name=m_full_name+",";
				m_address=m_full_name+","+m_add1+","+m_add2+","+m_city_name;
				m_address_name=m_full_name;
				m_address1=m_add1+","+m_add2;
				m_address2=m_city_name;
				}
				else if(!m_full_name.equals("-") && !m_add1.equals("-") && !m_add2.equals("-") && m_city_name.equals("-") )	{
				m_address=m_full_name+","+m_add1+","+m_add2;
				m_address_name=m_full_name;
				m_address1=m_add1+","+m_add2;
				m_address2=" ";
				}
				else if(!m_full_name.equals("-") && !m_add1.equals("-") && m_add2.equals("-") && !m_city_name.equals("-") ){
				m_address=m_full_name+","+m_add1+","+m_city_name;	
				m_address_name=m_full_name;
				m_address1=m_add1;
				m_address2=m_city_name;
				}
				else if(!m_full_name.equals("-") && m_add1.equals("-") && m_add2.equals("-") && !m_city_name.equals("-") ){
				m_address=m_full_name+","+m_city_name;
				m_address_name=m_full_name;
				m_address1=m_add1+","+m_add2;
				m_address2=" ";
				}
				else if(!m_full_name.equals("-") && m_add1.equals("-") && m_add2.equals("-") && m_city_name.equals("-") )	{
				m_address=m_full_name;
				m_address_name=m_full_name;
				m_address1=" ";
				m_address2=" ";
				}
				
				
				out.println("<table class='table'  width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class='table'> "+
				" <tr> "+
				" <td width=\"60%\" class='rep-body1' height='20px;' align=left><b>"+m_ven_name+"</b></td> "+
				" <td width=\"12%\" class='rep-body1' height='20px;' align=left><b>Order No </b></td> "+

				" <td width=\"3%\"  class='rep-body1' height='20px;' align=center><b>:</b></td> "+
				" <td width=\"25%\" class='rep-body1' height='20px;' align=left><b>"+m_purch_order_no+"</b></td> "+
				" </tr> "+
				" <tr> "+
				" <td class='rep-body1' align=left height='20px;'><b>"+m_ven_add+"</b></td> "+
				" <td class='rep-body1' align=left height='20px;'><b>Ref No</b></td> "+

				" <td class='rep-body1' align=center height='20px;'><b>:</b></td> "+
				" <td class='rep-body1' align=left   height='20px;'><b>"+m_finance_no+"</b></td> "+
				" </tr> "+
				" <tr> "+
				" <td class='rep-body1' align=left   height='20px;'><b>"+m_ven_city+"</b></td> "+
				" <td class='rep-body1' align=left   height='20px;'><b>Date</b></td> "+

				" <td class='rep-body1' align=center height='20px;'><b>:</b></td> "+
				" <td class='rep-body1' align=left   height='20px;'><b>"+m_Letter_date+"</b></td> "+
				" </tr> "+
				" <tr> "+
				" <td class='rep-body1' align=left  height='20px;'>&nbsp;</td> "+
				" <td class='rep-body1' align=left  height='20px;'>&nbsp;</td> "+

				" <td class='rep-body1' align=center height='20px;'>&nbsp;</td> "+
				" <td class='rep-body1' align=left   height='20px;'>&nbsp;</td> "+
				" </tr> "+
				" </table> ");
				
				//Empty Table to Incease Gap
			  out.println("<table border='0' width='100%' class='table'><tr><td height='10px;'></td></tr></table>"); 			
			
				
			  out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">"); 		
			  out.println("<tr>");
			  out.println("<td width='*%' class='rep-body1' style='text-align:justify' height='20px;' >Dear Sir/Madam</td>");
			  out.println("</tr></table>");

			String data="<b>We, "+m_company_name.toUpperCase()+"</b> hereby place our official Delivery Order/ Supply Agreement "+
			"to you for the Equipment/s in connection with our lease purchase arrangement with "+
			"<b>"+m_full_name+"  of "+
			" "+m_add1+"&nbsp"+m_add2+"&nbsp"+m_city_name+"</b> ";
			
			
			//Empty Table to Incease Gap
			out.println("<table border='0' width='100%' class='table'><tr><td height='20px;'></td></tr></table>"); 			
			
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">"); 		
			out.println("<tr>");
			out.println("<td width='*%' class='rep-body1' style='text-align:justify' height='20px;' >"+data+"</td>");
			out.println("</tr></table>");
			
			//Empty Table to Incease Gap
			out.println("<table border='0' width='100%' class='table'><tr><td height='20px;'></td></tr></table>"); 			
			
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">");
			out.println("<tr><td width='2%' class='rep-body1' style='text-align:left'><b>1.</b></td>");
			out.println("    <td width='*%' class='rep-body1' style='text-align:left'><b>Schedule</b></td>");
			out.println("</tr>");
			out.println("</table>");
			
			rs=stmt.executeQuery (sql);
			
			while(rs.next()){
			m_Eng_no=rs.getString(2);
			m_Chas_no=rs.getString(3);
			m_Reg_no=rs.getString(4);
			m_Qty=rs.getDouble(5);
			m_Qty2=rs.getString(5);
			m_Descr=rs.getString(6);
			m_Extras=rs.getString(7);
			m_Net_Amt=rs.getDouble(8);
			
			//Empty Table to Incease Gap
			out.println("<table border='0' width='100%' class='table'><tr><td height='20px;'></td></tr></table>"); 			
			
			out.println("<table border='1' width=\"100%\" class='table' bordercolor='black' cellspacing=\"0\" cellpadding=\"0\" >");
			out.println("<tr><td width='40%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>Description of the vehicle/equipment</b></td>");
			out.println("    <td width='60%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>"+m_Descr+" &nbsp - "+m_Qty2+"</b></td></tr>");
			out.println("<tr><td width='40%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>Registration No.</b> </td>");
			out.println("    <td width='60%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>"+m_Reg_no+"</b> </td></tr>");
			out.println("<tr><td width='40%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>Engine No.</b></td> ");
			out.println("    <td width='60%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>"+m_Eng_no+"</b></td></tr>");
			out.println("<tr><td width='40%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>Chassis No./Serial No.</b></td>");
			out.println("    <td width='60%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>"+m_Chas_no+"</b></td></tr>");
			out.println("<tr><td width='40%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>Extras included.</b></td>");
			out.println("    <td width='60%' class='rep-body1' style='text-align:left' height='30px;'>&nbsp <b>"+m_Extras+"</b></td></tr>");
			out.println("</table>");
			
      m_tot_amt = m_tot_amt + m_Net_Amt; 
      }						
				
			rs=stmt.executeQuery (" SELECT "+m_tot_amt+" FROM DUAL ");
			if(rs.next()){
			m_Amount_wd=rs.getString(1);
			}
			
			/*data="Please return the duplicate of this Delivery Order with an endorsement from the Lease Purchaser stating "+
			"that they have received same. ";
			*/
			//Empty Table to Incease Gap
			out.println("<table border='0' width='100%' class='table'><tr><td height='20px;'></td></tr></table>"); 									 
			
		
			data="Rs."+nf.format(m_tot_amt)+" (Rupees.  "+m_sn_methods.numbersToChar(m_Amount_wd)+" Only.)";
			
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">");
			out.println("<tr><td width='3%' class='rep-body1' style='text-align:left'><b>2.</b></td>");
			out.println("    <td width='20%' class='rep-body1' style='text-align:left'><b>Purchase Price:</b></td>");
			out.println("    <td width='*%' class='rep-body1' style='text-align:left'><b>"+data+"</b></td>");
			out.println("</tr>");
			out.println("</table>");
			
			out.println("<table border='0' width='100%' class='table'><tr><td height='20px;'></td></tr></table>"); 									 
			
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">");
			
			out.println("<tr><td width='3%' class='rep-body1' style='text-align:left'  height='15px;'><b>3.</b></td>");
			out.println("    <td width='20%' class='rep-body1' style='text-align:left' height='15px;'><b>Place to be delivered:</b></td>");
			out.println("    <td width='*%' class='rep-body1' style='text-align:left'  height='15px;'><b>"+m_full_name+"</b></td>");
			out.println("</tr>");
			out.println("<tr><td width='3%' class='rep-body1' style='text-align:left'  height='15px;'>&nbsp;</td>");
			out.println("    <td width='20%' class='rep-body1' style='text-align:left' height='15px;'>&nbsp;</td>");
			out.println("    <td width='*%' class='rep-body1' style='text-align:left'  height='15px;'><b>"+m_address1+"</b></td>");
			out.println("</tr>");
			out.println("<tr><td width='3%' class='rep-body1' style='text-align:left'  height='15px;'>&nbsp;</td>");
			out.println("    <td width='20%' class='rep-body1' style='text-align:left' height='15px;'>&nbsp;</td>");
			out.println("    <td width='*%' class='rep-body1' style='text-align:left'  height='15px;'><b>"+m_address2+"</b></td>");
			out.println("</tr>");
			
			out.println("</table>");
			

			out.println("</td></tr></table>");
			//Empty Table to Incease Gap
			//out.println("<table border='0' width='100%' class='table'><tr><td height='320px;'></td></tr></table>"); 			
			
			//Signature Printing
			String m_sign="";
			if (m_approved_user.equals("NISHAMAN")) {
			m_sign="sign1.gif";
			}else if (m_approved_user.equals("DILUM")) {
			m_sign="sign2.gif";
			}else if (m_approved_user.equals("SUSANTHA")) {
			m_sign="sign3.gif";
			}else if (m_approved_user.equals("SURANGA")) {
			m_sign="sign4.gif";
			}
			else if (m_approved_user.equals("ASINI")) { 
			m_sign="sign5.gif";
			}
			else if (m_approved_user.equals("NILANTHAJ")) { //added by thamali on 28-12-2011
					m_sign="sign6.gif";
			}
			else{
			m_sign="sign1.gif";
			}
			
			/*out.println("<table border='0' bordercolor='black' cellspacing='0' width='100%' class='table' align='left'>"); 
			out.println("<tr><td width='*%' class='rep-body1' align='left'><img src='"+m_html_client_url+"/"+m_sign+"'></td></tr>");
			out.println("</table>");
			*/
			
			if(m_ven_type.trim().equals("I") || m_ven_type.trim().equals("IND") || m_ven_type.trim().equals("INDIVIDUAL")  ){ 
			mm_rubber_seal_string="";
			}
			else{
			mm_rubber_seal_string="Co. rubber stamp to be placed";
			m_ven_name="Authorised Signatory";
			}
			
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">"); 		
			out.println("<tr><td width='70%' class='rep-body1' ><img src='"+m_html_client_url+"/"+m_sign+"'></td>");
			out.println("    <td width='30%' class='rep-body1' valign='top' style=\"{text-align='center'}\" ><p><br><br><br><br><br>"+m_ven_name.toUpperCase()+"<br>"+mm_rubber_seal_string+"</p></td></tr>");
			//out.println("<tr><td width='50%' class='rep-body1' >&nbsp;</td>");
			//out.println("    <td width='50%' class='rep-body1'              style=\"{text-align='center'}\">"+mm_rubber_seal_string+"</td></tr>");
			out.println("</table>");			
			
			//Empty Table to Incease Gap
			out.println("<table border='0' width='100%' class='table'><tr><td height='300px;'></td></tr></table>"); 			//310
			mm_rubber_seal_string="";
			out.println("<table border='0' width=\"100%\" class='table' cellspacing=\"0\" cellpadding=\"0\">"); 		
			out.println("<tr><td width='*%' class='rep-body1' >&nbsp;<p>"+m_full_name.toUpperCase()+"<br>"+mm_rubber_seal_string+"</p></td></tr>");
			//out.println("<tr><td width='40%' class='rep-body1' >"+mm_rubber_seal_string+"</td></tr>");
			out.println("</table>");			
	    out.println("</form></body></html>");
			}
			out.flush();
		}
		catch (Exception ex) {
		try{out.println("Error:"+ex.toString());}catch(Exception e){}
		}
		finally{
		    if(conn!=null){try{conn.close();  }catch(Exception e){}}
				if(out!=null){try{out.close();  }catch(Exception e){}}
		}
	}
}
